### ISSUE TITLE
[QUESTION][Arch Floppy Setup] Scan & Connect to WiFi networks

### ISSUE THREAD

**Issue by cacheiforindicium** [manilarome/the-glorious-dotfiles#102]
Hi,

I have some questions regarding wireless networks.
Whenever I click on the network widget in the systray, it takes me to nm-applet where I can manually add networks. However, I would like to scan which networks are available and connect to them automatically. What could I use for this?

Secondly, I really like the notification bar for emails, but it gives me the following error: "Check network connection!" In the network widget it also says "Connected to: N/A", so I think these issues are related to each other. I read in a previous issue that this is due to an instable connection. However, I don't think this is the case. I have a great WiFi strength with a network speed of over 200 Mbps. I'm wondering what else could cause this.

**Comment by manilarome** [comment]
> I have some questions regarding wireless networks.
Whenever I click on the network widget in the systray, it takes me to nm-applet where I can manually add networks. However, I would like to scan which networks are available and connect to them automatically. What could I use for this?

Install network manager applet then run it by `nm-applet`. Then open the systemtray widget.

![image](https://user-images.githubusercontent.com/40349590/80592650-5d91a980-8a52-11ea-9fa0-0c8ef5125dcd.png)

> it gives me the following error: "Check network connection!" In the network widget it also says "Connected to: N/A"

Make sure to change these lines: https://github.com/manilarome/the-glorious-dotfiles/blob/4435a0ec915bbd56e42c97960e58e7ca3573fa6e/config/awesome/floppy/widget/network/init.lua#L27-L28

**Comment by cacheiforindicium** [comment]
Hi, thanks for your fast reply.

nm-applet did the trick for me.

I've changed the lines to my actual interfaces

`
local wlan_interface = 'wlp82s0'
local lan_interface = 'enp0s31f6'`

However, I'm still gettting the same issue. It only shows the WiFi interface and strength in the widget, the rest is N/A. It does display the correct interface (wlp82s0)

**Comment by manilarome** [comment]
> However, I'm still gettting the same issue. It only shows the WiFi interface and strength in the widget, the rest is N/A. 

Weird. What is the output of:
```bash
$ iw dev wlp3s0 link 
```

**Comment by cacheiforindicium** [comment]
Apparently installing iw resolved the issue with the network not being shown in the widget. For some reason in the notifications it still says check network connection.

```
Connected to ac:22:05:78:2c:1d (on wlp82s0)
	SSID: Home-5GHZ
	freq: 5180
	RX: 669003 bytes (1930 packets)
	TX: 154460 bytes (925 packets)
	signal: -58 dBm
	rx bitrate: 585.1 MBit/s VHT-MCS 6 80MHz short GI VHT-NSS 2
	tx bitrate: 81.0 MBit/s VHT-MCS 2 40MHz VHT-NSS 2

	bss flags:	short-preamble short-slot-time
	dtim period:	1
	beacon int:	100
```

**Comment by manilarome** [comment]
> For some reason in the notifications it still says check network connection.

Yeah that notification is annoying. You can change these [lines](https://github.com/manilarome/the-glorious-dotfiles/blob/d856680040a46d609c52af519ee65618010a3fea/config/awesome/floppy/widget/network/init.lua#L231-L249) to suppress it. I'm planning to find an alternative to check the wi-fi connection's health.

**Comment by manilarome** [comment]
I changed ping with [curl](https://github.com/manilarome/the-glorious-dotfiles/blob/b56dc1c7f5f55a61ddbc0371e156f47b067a6fde/config/awesome/floppy/widget/network/init.lua#L267-L272). It's better and more consistent than pinging google. It's not perfect so if you want to completely disable the notification, comment https://github.com/manilarome/the-glorious-dotfiles/blob/b56dc1c7f5f55a61ddbc0371e156f47b067a6fde/config/awesome/floppy/widget/network/init.lua#L244.

Hopefully I can find a better way to check the internet connection. Closing this for now. Reopen again if you're not satisfied with this solution. Thanks!
