### ISSUE TITLE
[BUG] Lockscreen crash if screen 1 is being removed

### ISSUE THREAD

**Issue by PtitCaius** [manilarome/the-glorious-dotfiles#107]
# Actual setup
- awesome v4.3-826-g29f6387 (Too long)
 • Compiled against Lua 5.3.1 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.4
 • LGI version: 0.9.1
 • Transparency enabled: yes
 • Custom search paths: no
- Ubuntu 16.04

# Bug description
The lockscreen crashes if the screen with index = 1 is being removed. I can trigger this behavior when I change my screen configuration with autorandr, wich remove my laptop screen and add my desktop one. 

It seems that the screen's request::desktop_decoration signal is not fired when i change my configuration, without reloading awesome.

# Fix proposition

After a very quick search I was able to fix the issue with :
```
screen.connect_signal("added", function(s)
	for s in screen do 
		if s.index == 1 then
			s.lockscreen = locker(s)
		else
			s.lockscreen_extended = locker_ext(s)
		end
	end

end)

screen.connect_signal("removed", function(s)

	for s in screen do 
		if s.index == 1 then
			s.lockscreen = locker(s)
		else
			s.lockscreen_extended = locker_ext(s)
		end
	end

end)
```

It might not be a good solution but it should do the trick.

**Comment by manilarome** [comment]
Thanks for this! I'm planning to rewrite the lockscreen module (it's kinda messy right now). I'll make sure to implement your code. Thanks again! :)

**Comment by manilarome** [comment]
I applied your fix here https://github.com/manilarome/the-glorious-dotfiles/commit/832e241a5aae4eaaf96de8d13ac43ef634a6201b. Thanks again!

**Comment by PtitCaius** [comment]
You're welcome !
