### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by xieve** [manilarome/the-glorious-dotfiles#110]
This is a great project, but technically still not really "free". I'd suggest licensing under the AGPL, to make sure all derivatives will benefit the project.

**Comment by manilarome** [comment]
Currently it's GPL3. Should I change it to Affero GPL?

**Comment by manilarome** [comment]
Done https://github.com/manilarome/the-glorious-dotfiles/commit/5502debcd20d6dcd42feb7ac50d8210c44feb382

**Comment by xieve** [comment]
I didn't find a LICENSE file prior to this, I think, that's mainly why I created the issue :sweat_smile: 
The change from GPL to AGPL probably doesn't really affect this particular project, because it's not revolving around any server applications.
