### ISSUE TITLE
Lock screen not validating password

### ISSUE THREAD

**Issue by Ahira-hub** [manilarome/the-glorious-dotfiles#112]
Sorry, but I'm back again :(
As the title mentions, any time I lock the screen I'm not able to log back in. Only way I can log back in is to reboot. In apps.lua, I did add the kde polkit as the gnome polkit caused apps not to authenticate when needed. 

Kubuntu 20.04

**Comment by manilarome** [comment]
Uhm... the lockscreen module uses PAM as authenticator, it should work without polkit-(gnome/kde). Please send your logs for more information. Assuming your using SDDM as display manager because you are using Kubuntu, please run `tail -f -n 30 ~/.local/share/sddm/xorg-session.log > awesome-log.txt`  then lock the screen. After locking try to press <kbd>Super + Ctrl + R</kbd>, if there's an error in the lockscreen module, awesomewm should restart.

**Comment by Ahira-hub** [comment]
So interestingly enough, the logs were blank. I couldn't restart awesome so I had to reboot. Now I can't login to awesome at all. It just goes black and kicks me back to login prompt :(.

**Comment by manilarome** [comment]
I think you should reinstall AwesomeWM or something. If the setup produces the error, it should throw an error instead of locking you out of your system. You can also try to use the default `rc.lua` to debug. Please, consider checking your system log using `journalctl -xe`.

**Comment by Ahira-hub** [comment]
Ok. I'm back in now (thank goodness for backups). Still having the PAM issue though. Is there any dependency or setup for PAM? I didn't see anything I was supposed to configure in the wiki.

**Comment by manilarome** [comment]
The only dependency is **PAM**. Please, check if you have it installed. You can also debug it using **Xephyr**(best way to do it).

**Comment by Ahira-hub** [comment]
Thanks for the input. PAM is indeed installed. I'm new to Linux and have no idea how to use Xephyr. Would it be possible to disable the lock screen, and revert to the built-in one? I don't mind troubleshooting this PAM one, but I don't know if I can do that effectively.

**Comment by manilarome** [comment]
> Would it be possible to disable the lock screen, and revert to the built-in one?

You can disable it by commenting this line `require('module.lockscreen')
` in rc.lua.

> have no idea how to use Xephyr 

You can follow this [guide](https://wiki.archlinux.org/index.php/Awesome#Debugging_rc.lua) from archwiki.

>  I don't mind troubleshooting this PAM one, but I don't know if I can do that effectively.

Goodluck mate!

**Comment by Ahira-hub** [comment]
After hours of troubleshooting this, the closest I could find is this bug:
https://bugs.kde.org/show_bug.cgi?id=380491
The workaround doesn't resolve the issue unfortunately. Also interesting, the login attempt is not logged into any of the logs, /var/log/auth.log, xsession, etc. It's like the attempt was never made.

**Comment by manilarome** [comment]
Hmmm... must be PAM issue. I will investigate.

**Comment by manilarome** [comment]
Can you please try to clone and build [this](https://github.com/RMTT/lua-pam). It's a library we are using to authenticate with PAM. Then in the same directory of the libary put this script:

```lua
#!/usr/bin/env lua


package.cpath = package.cpath .. ";" .. "/PATH_TO_LIBARY/?.so;"
local pam = require('liblua_pam')
password = 'PUTYOURPASSWORDHERE'
local auth = pam.auth_current_user(password)
if auth
then
    print("Success!")
end

```

**Comment by manilarome** [comment]
> the login attempt is not logged into any of the logs, /var/log/auth.log, xsession, etc. It's like the attempt was never made.

Uhh it also doesn't create any logs here. Maybe, because we're not logging in? Just unlocking the screen. I guess that the library is just authenticating if the user input is the same as the user password. I'm probably wrong here tho haha

**Comment by Ahira-hub** [comment]
Well, thank you for everything, but I'm just going to disable the lockscreen. I can't get that package to build (missing lua.hpp, even though it's in /include). I don't want to take any more of your time. Thank you again!!! It's a great setup for a Linux noob like me and got me into ricing :)

**Comment by manilarome** [comment]
> missing lua.hpp, even though it's in /include

Maybe that's the problem! I think you're missing a lua library? But it's weird because lua is a dependency of awesomewm. 

> I don't want to take any more of your time. Thank you again!!! It's a great setup for a Linux noob like me and got me into ricing :)

No problem mate. You're free to ask a question. Goodluck!

**Comment by Ahira-hub** [comment]
Thanks :) I've installed every lua I can find. I may even do a fresh install on an old laptop just to test. I'll let you know. Feel free to close this for now. Thanks again.
