### ISSUE TITLE
[FEATURE REQUEST][ALL] Better Multihead Support (Hotplugging)

### ISSUE THREAD

**Issue by xieve** [manilarome/the-glorious-dotfiles#116]
Basically, whenever a monitor is added or removed, the user has to manually call xrandr/autorandr, then restart AwesomeWM and hope that it doesn't spit errors (next time it does this, I should probably look at the logs). Another problem is that the lockscreen can easily be circumvented by attaching another monitor.

**Comment by manilarome** [comment]
I'll look into it.

**Comment by manilarome** [comment]
Please test the [latest commit](https://github.com/manilarome/the-glorious-dotfiles/commit/f738311feda1365e1a8de92ca43426aff5096c40). I think it should work now.
