### ISSUE TITLE
[QUESTION][ROFI] Global Search/App launcher not launching

### ISSUE THREAD

**Issue by strachanbrad** [manilarome/the-glorious-dotfiles#118]
I can't figure out why rofi global search or app menu will not launch. When I click on global search or use the key binding the left panel immediately closes. There is no action from clicking the app launcher at all. I can execute the app.defaults commands with success from the terminal. I believe I have traced my problem to the _G.awesome.spawn() call in the panel:runrofi() function in layout.leftpanel, but im not sure. I don't know the implementation of _G.awesome.spawn() either. If you have any insight it would be greatly appreciated.

**Comment by manilarome** [comment]
What setup are you using? Also, please try to change `_G.awesome.spawn()` with `awful.spawn()`

**Comment by manilarome** [comment]
You can also check your xsession logs for more information that can help us.

**Comment by strachanbrad** [comment]
I changed it `awful.spawn()` which does behave better. I'm not getting the closing of the panel anymore, and widgets are hiding as expected. 

Xsession is getting a warning that rofi can't set the locale. No errors though. This does confirm that the app launcher is running the `apps.default` command however.

**Comment by strachanbrad** [comment]
And sorry I'm running floppy

**Comment by strachanbrad** [comment]
When I reload awesome I get this error. It may be related.

2020-05-28 23:31:08 E: awesome: Error during a protected call: attempt to compare number with nil
stack traceback:
	[C]: in function 'math.min'
	/usr/share/awesome/lib/wibox/widget/slider.lua:344: in function 'wibox.widget.slider.set_value'
	.../krachen/.config/awesome/widget/volume/volume-slider.lua:93: in function <.../krachen/.config/awesome/widget/volume/volume-slider.lua:89>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:487: in function </usr/share/awesome/lib/awful/spawn.lua:481>
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
	/usr/share/awesome/lib/awful/spawn.lua:601: in function </usr/share/awesome/lib/awful/spawn.lua:593>

**Comment by strachanbrad** [comment]
It was a locale issue I had my locale set to en_CA.UTF-8 after changing to en_US.UTF-8 in locale.gen and running locale-gen rofi is working great.

I'm a novice to linux and new to arch. Your direction with troubleshooting and consideration was very helpful. And also thank you for your timely response.

**Comment by manilarome** [comment]
> It was a locale issue I had my locale set to en_CA.UTF-8 after changing to en_US.UTF-8 in locale.gen and running locale-gen rofi is working great.

Glad you fixed it! 

> I'm a novice to linux and new to arch. Your direction with troubleshooting and consideration was very helpful. And also thank you for your timely response.

No problem! Happy hacking!
