### ISSUE TITLE
[QUESTION[Floppy] Hotkeys Help is centered on screen 2

### ISSUE THREAD

**Issue by ArtemSmaznov** [manilarome/the-glorious-dotfiles#120]
I have a dual screen setup with secondary screen being placed on the left and positioned vertically.

For some reason when I launch hotkeys help from the main screen via MOD+F1 it opens centered on the second screen and goes off-screen and I cannot seem to find how to force it to screen 1 at all times?
![20200530_110641](https://user-images.githubusercontent.com/31800376/83325711-44a13180-a266-11ea-9d09-cf4334a2fc50.jpg)

Is the position of the widget set up in the rules? Or do I need to modify the widget itself?

Weirdly enough if I trigger MOD+F1 from the second screen it opens centered on screen 2 with no off-screen leak.

**Comment by manilarome** [comment]
> I have a dual screen setup with secondary screen being placed on the left and positioned vertically.

Can you please try to reproduce this on a vanilla rc.lua? Right now, I'm only on a single monitored setup, so I cannot test it.  

> Is the position of the widget set up in the rules? Or do I need to modify the widget itself?

No, I didn't set any rules for it, just keybind <kbd>mod + f1</kbd>.

**Comment by ArtemSmaznov** [comment]
Thanks for the confirmation. 

I would imagine that this is due to the git version of awesome as I didn't have it with the standard version. Will play around with different configs and update here afterwards.

Loving the setup so far so thanks for sharing - your work is amazing.

**Comment by ArtemSmaznov** [comment]
OK I can confirm that I am seeing the same behavior with vanilla config.
If I install the stable version of AwesomeWM then the issue goes away so it is indeed a problem with the development version.

I might submit a PR for a workaround if I can figure it out.
