### ISSUE TITLE
[CLARIFICATION] add missing optional dependency for xdg-folders widget

### ISSUE THREAD

**Issue by Choco3-3** [manilarome/the-glorious-dotfiles#121]
`xdg-folders` widget for the folder buttons requires the dependency `xdg-user-dirs` available on `pacman` that is included in some but not all Desktop Environments (Eg. GNOME). 

Thus, I suggest you add this in as part of the option dependencies in your wiki to clear up confusion on some people who use DE's like `Xfce` which do not have the dependency preinstalled.

**Comment by manilarome** [comment]
Updated the dependency list. Thanks!

**Comment by ildar** [comment]
I wonder if Awesome api works without the utility?
https://github.com/manilarome/the-glorious-dotfiles/issues/79#issuecomment-611549917

-- 
Ildar Mulyukov,
(ΙΧΘΥΣ) child of God

email: ildar.mulyukov@gmail.com
matrix: @ildar:matrix.org
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/


вс, 31 мая 2020 г., 4:13 Gerome Matilla <notifications@github.com>:
