### ISSUE TITLE
[BUG][Floppy] Fix Lock Screen on dual monitor setups

### ISSUE THREAD

**Issue by ArtemSmaznov** [manilarome/the-glorious-dotfiles#122]
### Issue:
Currently locking the screen will position the lockscreen on the top left corner even if that means spanning it across multiple screens (if the secondary screen is on the left). Some areas of the desktop remain and are fully intractable (user can right click and choose to restart AwesomeWm from the menu to bypass the lockscreen).
![20200530_191655](https://user-images.githubusercontent.com/31800376/83336358-adaa9880-a2aa-11ea-8b73-29b7dc50cc10.jpg)

### Fix:
Adding `screen = s` to `lockscreen` fully fixes the issue with my setup. Lockscreen now fully covers the primary screen and extends to secondary screen

**File:**
module/lockscreen.lua

```
	local lockscreen = wibox {
		visible = false,
		ontop = true,
		type = "splash",
		width = s.geometry.width,
		height = s.geometry.height,
		bg = beautiful.background,
		fg = beautiful.fg_normal
	}
```
add `screen = s`: 
```
	local lockscreen = wibox {
		screen = s,
		visible = false,
		ontop = true,
		type = "splash",
		width = s.geometry.width,
		height = s.geometry.height,
		bg = beautiful.background,
		fg = beautiful.fg_normal
	}
```

**Comment by manilarome** [comment]
Thanks for this! https://github.com/manilarome/the-glorious-dotfiles/commit/f738311feda1365e1a8de92ca43426aff5096c40

**Comment by ArtemSmaznov** [comment]
No probs, I actually didn't put the screen to the extended_lockscreen object and it was working fine for both screens. Let me quickly check if that breaks anything

**Comment by ArtemSmaznov** [comment]
No difference at all with screen there. Guess it makes sense to have it is as well.

**Comment by manilarome** [comment]
Yeah I also added the screen property to it as well. Thanks again!
