### ISSUE TITLE
[Question] Errors popping out upon installation

### ISSUE THREAD

**Issue by iskmar** [manilarome/the-glorious-dotfiles#124]
I am getting these errors upon installation. I installed floppy on vbox and it worked but when I tried to do it on my production machine, it started popping errors. Installed all the required dependencies but to no avail.
![101398836_258415038743316_5364982793489088512_n](https://user-images.githubusercontent.com/15051230/83365921-19c0f580-a3ac-11ea-9717-b7406440be3b.jpg)

Sorry for uploading bad quality pic.

**Comment by manilarome** [comment]
You need to install the **git/master** branch of awesome
