### ISSUE TITLE
[Multi-Monitor Support][gnawesome] Disabling Top and Dock on secondary monitor

### ISSUE THREAD

**Issue by Echo2124** [manilarome/the-glorious-dotfiles#125]
Hello there,

If there any ability to disable the top menu (with the time and all that stuff) and the dock (bottom) on the secondary monitor. In order to only have it show on the primary monitor. Its kinda weird having two docks if you get my drift. Either way, great work. You've done an amazing job on this.

Thanks

**Comment by manilarome** [comment]
Replace these [lines](https://github.com/manilarome/the-glorious-dotfiles/blob/f738311feda1365e1a8de92ca43426aff5096c40/config/awesome/gnawesome/layout/init.lua#L7-L13). With this snippet:

```lua
screen.connect_signal("request::desktop_decoration", function(s)
	if s.index == 1 then
		s.top_panel = top_panel(s, false)
		s.bottom_panel = bottom_panel(s)
		s.floating_panel = floating_panel(s)
		s.floating_panel_show_again = false
	end
end)
```

**Comment by Echo2124** [comment]
Thank you for your help. Your solution worked. You can close this issue if you wish.
