### ISSUE TITLE
[BUG][Floppy] Screen recorder ffmpeg settings

### ISSUE THREAD

**Issue by danimateo** [manilarome/the-glorious-dotfiles#126]
Hello, I played around with ffmpeg settings for the screen recorder widget because there were some compatibility problems with WhatsApp for example when sending the video. I reached the config below that seems to work fine. Also, maybe a quality setting in the widget would be nice? I set it to 20 here in the `crf` argument.

`	ffmpeg -video_size ]] .. user_resolution .. [[ -framerate ]] .. user_fps .. [[ -f x11grab \
		-i :0.0+]] .. user_offset .. add_audio_str .. [[ -c:v libx264 -crf 20 -profile:v baseline -level 3.0 -pix_fmt yuv420p $file_name
		]],
`

**Comment by manilarome** [comment]
>  there were some compatibility problems with WhatsApp for example when sending the video. 

Please elaborate. The widget only uses ffmpeg to record stuff. Please, try to run the command in terminal and replace the variables with your settings. A log can also be helpful. 

> ffmpeg -video_size ]] .. user_resolution .. [[ -framerate ]] .. user_fps .. [[ -f x11grab \ -i :0.0+]] .. user_offset .. add_audio_str .. [[ -c:v libx264 -crf 20 -profile:v baseline -level 3.0 -pix_fmt yuv420p $file_name ]],

Aside from `crf 20`, is this your custom ffmpeg command? It's different from the script in the widget. 

> Also, maybe a quality setting in the widget would be nice?

Will do if I find the time. My hands are currently full right now.

**Comment by danimateo** [comment]
It was a suggestion to replace the command in the script with what I have provided. Sorry if it wasn't clear. It has some backwards compatibility with older players and so.

**Comment by manilarome** [comment]
Thanks for the clarification. Anyway, I can't implement the GUI for quality settings right now. Maybe in a week or two. I'm jusy really busy. Please, don't close this yet.

**Comment by danimateo** [comment]
I have time, I can make a pull request if that's ok with you?

**Comment by manilarome** [comment]
Yes, please. Thanks!

**Comment by manilarome** [comment]
It took some time but I implemented your ffmpeg script https://github.com/manilarome/the-glorious-dotfiles/commit/b2168c61479ad88daddc567786e0255d172cacdc. Thank you!
