### ISSUE TITLE
[FEATURE REQUEST][Floppy] Replacing Screenshot Binary

### ISSUE THREAD

**Issue by ArtemSmaznov** [manilarome/the-glorious-dotfiles#128]
I have noticed somewhere that you mentioned that you are trying to get rid of the binaries.
I have been working on converting the screenshot binary to a module and have already done most of the work.

The only thing that I cannot figure out is how to get the thumbnails back but here is the file if you are interested in trying to change it. Feel free to close this if this is not how you wanted to approach this.

Also added a way to make a screenshot of the active screen.

```
local naughty = require('naughty')
local awful = require('awful')

return function(mode)
	local screenshot_dir = os.getenv('HOME') .. '/Pictures/Screenshots/'
	local file_loc = screenshot_dir .. os.date("%Y-%m-%d_%T") .. '.png'
	local maim_command, notif_message

	if (mode == 'full') then
		maim_command = 'maim -u -m 1 '
		notif_message = "Full screenshot saved and copied to clipboard!"

	elseif (mode == 'window') then
		maim_command = 'maim -u -B -i $(xdotool getactivewindow) -m 1 '
		notif_message = "Current window screenshot saved and copied to clipboard!"

	elseif (mode == 'area') then
		maim_command = 'maim -u -s -n -m 1 '
		notif_message = "Area screenshot saved and copied to clipboard!"

	else
		notif_message = "Wrong Argument Used!"
	end

	awful.spawn.easy_async_with_shell(maim_command .. file_loc, function()

		awful.spawn('xclip -selection clipboard -t image/png -i ' .. file_loc)

		local open_image = naughty.action {
			name = 'Open',
				icon_only = false,
		}

		local open_folder = naughty.action {
			name = 'Folder',
				icon_only = false,
		}

		local delete_image = naughty.action {
			name = 'Delete',
				icon_only = false,
		}

		-- Execute the callback when 'Open' is pressed
		open_image:connect_signal('invoked', function()
			awful.spawn('xdg-open ' .. file_loc, false)
		end)

		open_folder:connect_signal('invoked', function()
			awful.spawn('xdg-open ' .. screenshot_dir, false)
		end)

		-- Execute the callback when 'Delete' is pressed
		delete_image:connect_signal('invoked', function()
			awful.spawn('gio trash ' .. file_loc, false)
		end)

		-- Show notification
		naughty.notification ({
			app_name = 'Screenshot Tool',
			icon = file_loc,
			timeout = 10,
			title = '<b>Snap!</b>',
			message = notif_message,
			actions = { open_image, open_folder, delete_image }
		})
	end)

end
```
To call it use something like this (based on file name and location):
`require('module.screenshot')('full')`

**Comment by ildar** [comment]
I'm sorry, binary liberation was my idea/ request.
AFAIK screenshots made by standard ‘xclip’ utility. And you effectively
replace it with some ’maim’ utility.
What's the advantage?

**Comment by ArtemSmaznov** [comment]
Actually it was main all along. All I did was take the Lua code from the screenshot binary as it was and convert the bash parts into Lua as much as I could. 

Files are not vastly different (compare screenshot binary with what I provided and you will see) but I did miss a few minor things like cancelling the screenshot logic and for some reason the notification in my file is triggered before the screenshot is actually taken which is why the thumbnail is not loaded.

And as I am writing this I realise that I forgot to add the xclip part to save screenshots to clipboard so will look at that tomorrow. Should be just one line in the end to add it.

Will also try to resolve the missing thumbnail if I can.

**Comment by ildar** [comment]
Ah, I see! :)
One little tip: usually Pull-Request is easier and faster to accept by a
project leader.

**Comment by manilarome** [comment]
Thanks for this! The screenshot script was originally wrapped inside lua/awesome's api just like your request here, but there's an issue I cannot fix. That's the reason why I decided to make it a shell script and I think it's much easier to maintain.  But yeah, please open a pull request so I can test it. :) Thanks again!

**Comment by ArtemSmaznov** [comment]
Based on what you said I would like to work a lil bit more on it and fix the issues with notification timing. Will update afterwards.

Also I don't think I can create a PR as I am not a contributor. My understanding that PRs are created from new branches and I do not have write permissions to this repository. Or am I misunderstanding the flow?

**Comment by ArtemSmaznov** [comment]
ok I have added the xclip part and fixed the issue with missing thumbnails. As it stands right now I think it does exactly what it was with the binary but is a bit easier to follow IMHO.

I have edited my first message with the new code for now but will see if I can figure out how to make a PR or if I even can (sorry I'm new to collaborating on github)

**Comment by ArtemSmaznov** [comment]
Ok I had to download a second copy of your repository but I figured out how to make a PR so there is one open now

**Comment by ArtemSmaznov** [comment]
done in https://github.com/manilarome/the-glorious-dotfiles/pull/129
