### ISSUE TITLE
[BUG][Linear] Black background instead of opacity

### ISSUE THREAD

**Issue by Hkyx** [manilarome/the-glorious-dotfiles#130]
Hi there,

long time from my last post, but don't really found a why it appear... 
I got a regular problem, I use the opacity settings on the dock and shell config. But I got a regular bug these both objects which let them with full usage, icons... but the background is changing to black without a reason.

Anyone with this problem ? it can come from picom but ... 
intel graphic card so don't think it's a driver problem

**Comment by manilarome** [comment]
> but the background is changing to black without a reason.

Hm I think that's a compositor problem.

**Comment by Hkyx** [comment]
don't get more informatio but yes it's isolated to picom
-- Subject: Process 536330 (picom) dumped core
-- Process 536330 (picom) crashed and dumped core.

I close here, 

ty @manilarome
