### ISSUE TITLE
[BUG][Floppy] email subject cannot display correctly when there is CJK fonts

### ISSUE THREAD

**Issue by RMTT** [manilarome/the-glorious-dotfiles#131]
When i received the email from nintendo and spotify using japanese, it seems shows the hex code of the word.
![image](https://user-images.githubusercontent.com/20596599/84024195-00c3d000-a9bc-11ea-9d72-f1687645bb7d.png)
![image](https://user-images.githubusercontent.com/20596599/84024204-07524780-a9bc-11ea-9099-2177f57046bb.png)
I tried to change the font to a CJK font like sarasa, but it had no any changes.

**Comment by manilarome** [comment]
Maybe because of the `gears.string.xml_escape`. Try to remove it. It can be found [here](https://github.com/manilarome/the-glorious-dotfiles/blob/f738311feda1365e1a8de92ca43426aff5096c40/config/awesome/floppy/widget/email/init.lua#L334).

**Comment by RMTT** [comment]
> Maybe because of the `gears.string.xml_escape`. Try to remove it. It can be found [here](https://github.com/manilarome/the-glorious-dotfiles/blob/f738311feda1365e1a8de92ca43426aff5096c40/config/awesome/floppy/widget/email/init.lua#L334).

Sorry, nothing works.

**Comment by manilarome** [comment]
It turns out that imaplib is not decoding this. So the problem is in the
python script in the email widget. So I think we need to decode it first
before printing. The problem is I don't know how to do it. I got an error
when I use base64 decoder.

**Comment by RMTT** [comment]
> It turns out that imaplib is not decoding this. So the problem is in the python script in the email widget. I think we need to decode it first before printing. The problem is I don't know how to do it. I got an error when I use base64 decoder. [Relevant thread](https://stackoverflow.com/questions/55841229/decode-japanese-characters-to-base64)

Have solved, just a little changes : ) , #132

**Comment by manilarome** [comment]
Nice! Thank you! :)
