### ISSUE TITLE
[BUG/FEATURE REQUEST][ALL] Battery-notifier error on desktops / "Quickfix"

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [manilarome/the-glorious-dotfiles#138]
![20200622_081951](https://user-images.githubusercontent.com/13170204/85256275-6c457d00-b453-11ea-911f-8be7b1e80367.png)
Due to the battery notifier being pretty much useless on a desktop setup, I tend to be bombarded with that error every time I boot up.
One fix I've found to remedy to this, is in my case, to directly disable it.
Simply by commenting or removing the `require('module.battery-notifier')` line in the rc.lua file at the root awesome folder.
I wished to do an edit to the wiki to add this, but I doubt it is editable by everyone, that explains why I've created an issue instead.

**Comment by manilarome** [comment]
Thanks for this. I'll just add a checker if I have a time! Please, don't close this issue yet.

**Comment by manilarome** [comment]
https://github.com/manilarome/the-glorious-dotfiles/commit/369d55979b9940548c4c5b14330b4bbe58a09745 Please test

**Comment by PoorPocketsMcNewHold** [comment]
I can confirm. This fixes the error message on my end, after re-enabling with module with the updated one.

Thanks for fixing this! (Even if this isn’t needed at all for my use case).
