### ISSUE TITLE
[BUG][Floppy] Make the shell compaitble with Fish

### ISSUE THREAD

**Issue by Yash-Kaveeshwar** [manilarome/the-glorious-dotfiles#139]
When I login from SDDM, the awesome is started with all the theme options but all the apps in the apps.lua are not started.

**Comment by Yash-Kaveeshwar** [comment]
I have investigated more and the problem lies with fish shell, when using fish as default shell battery, network applet don't work. Picom is also not called when starting the Awesome session.

**Comment by manilarome** [comment]
Yep, bash is recommended. But it's possible to explicitly say to use bash, I just forgot to implement it months ago.

**Comment by Yash-Kaveeshwar** [comment]
I would appreciate if we can use fish shell, cause most of my script are written for fish and I would have to convert them to bash.

**Comment by manilarome** [comment]
Uhm sorry but I don't really plan to use fish. But you can run your fish scripts on startup by wrapping the callback on the line below with fish https://github.com/manilarome/the-glorious-dotfiles/blob/d00e53c146b14c73040442a4f55417231340e896/config/awesome/floppy/module/auto-start.lua#L16 

I don't know how to do it in fish but in bash you change it to `"bash -c 'pgrep -u $USER -x %s > /dev/null || (%s)'"`. Goodluck!

**Comment by Dohvakin** [comment]
Well I see that fish shell is now supported, I went back to Windows 10 for some time, will give this one try again when I can use Linux again. Anyway thanks
