### ISSUE TITLE
[BUG][Floppy] systray doesn't update when the systray is invisible

### ISSUE THREAD

**Issue by RMTT** [manilarome/the-glorious-dotfiles#142]
The systray doesn't update when it is invisible after booting into system, but when i toggle it to visible and open apps, it can update correctly.
Once i toggle it to visible, it can update correctly no matter it is visible.

**Comment by manilarome** [comment]
> The systray doesn't update when it is invisible after booting into system

I don't think we have a workaround with this. I think that systemtray needs to draw its items first to 'update' it. So opening/showing the system tray is a requirement to update the item.

**Comment by RMTT** [comment]
https://awesomewm.org/doc/api/classes/wibox.widget.systray.html#widget::redraw_needed  using this signal when a new client created?

**Comment by manilarome** [comment]
> using this signal when a new client created?

Yeah I think it's possible. Call that signal on `manage` signal so it will update the systray when a new client was opened

**Comment by manilarome** [comment]
Hey closing this now. If you want to reopen this, please reopen this again! Thanks!

**Comment by RMTT** [comment]
Sorry for that i forget this issue, i'm so busy recently,and this issue seems just a little problem when actual using.I will try to some solutions until i have enought time.

**Comment by manilarome** [comment]
No problem! :)
