### ISSUE TITLE
[QUESTION][Floppy] When using Brave as a default in tags, it wont open in designated tag.

### ISSUE THREAD

**Issue by Yash-Kaveeshwar** [manilarome/the-glorious-dotfiles#143]
So I was experimenting with switching to Brave from google chrome and found an unexpected behavior.  When setting brave as a default_app in tag init.lua it wont open in tag designated to it but where ever I called it. 

Expected Behavior
ctrl+shift+f
open brave on tag2, I am on tag 1

Observed Behavior 
Brave opens on tag1 along side my terminal.

My init.lua for tag.
{
		icon = icons.google_chrome,
		type = 'chrome',
		default_app = 'brave',
		screen = 1
},

**Comment by negativeExponent** [comment]
you are suppose to change your default apps here:
https://github.com/manilarome/the-glorious-dotfiles/blob/master/config/awesome/floppy/configuration/apps.lua#L12

**Comment by Yash-Kaveeshwar** [comment]
I am talking about default app as in when you open the terminal it opens in tag1, and not where you called the command from. Brave is not behaving that way and opening on say tag which is designated as games or editor.

**Comment by negativeExponent** [comment]
then its probably here: https://github.com/manilarome/the-glorious-dotfiles/blob/master/config/awesome/floppy/configuration/client/rules.lua#L143

youll need to add "Brave-browser" (or whatever the class name for your brave is)

**Comment by Yash-Kaveeshwar** [comment]
Yup working perfectly, thanks.

**Comment by negativeExponent** [comment]
unrelated but somewhat related before i try to open the issue. but are brave popups opening for you as expected when clicking on the notification? i havent had mine opened, notification window just closes whatever mouse button is used (already changes firefox references to brave where necessary).

**Comment by Yash-Kaveeshwar** [comment]
No it doesn't open when clicking on notification, I never had a problem
with that as I disable them anyway.
