### ISSUE TITLE
[BUG][Floppy] Wallpaper stretched across multiple monitors

### ISSUE THREAD

**Issue by animanoj** [manilarome/the-glorious-dotfiles#144]
Multiple monitors seems to stretch the wallpaper across both the screens instead of duplicating across both. I tried messing around with the wallpaper loading in `rc.lua` and in `module/dynamic-wallpaper.lua`, but either I'm doing it wrong or passing the screen to `gears.wallpaper.maximized` doesn't really help.

![Screenshot from 2020-06-28 18-12-57](https://user-images.githubusercontent.com/14035779/85963535-1731cb80-b96b-11ea-8d11-613609ecdd4f.png)

Any ideas?

**Comment by Hkyx** [comment]
same issue on my side

**Comment by manilarome** [comment]
Yep I designed it that way. But it's possible to just duplicate each wallpaper. The problem is I don't have my extra monitor right now so I can't fix/test it. Patches welcome! :)

**Comment by Hkyx** [comment]
Can you give us a way to solve that ? I'll check if I find the time for that.

**Comment by manilarome** [comment]
I found an old snippet from an old thread, basically you could just loop through every screen and use `gears.wallpaper`. 

```lua
    for s = 1, screen.count() do
        --gears.wallpaper.maximized(beautiful.wallpaper, s, true)
        if s < 2 then
          gears.wallpaper.maximized("path_to_image_one", s, true)
        else
          gears.wallpaper.maximized("path_to_image_two", s, true)
        end
    end
```

**Comment by AnthyG** [comment]
And as a fix for `module/dynamic-wallpaper.lua` the following is sufficient:

```lua
for s in screen do
	gears.wallpaper.maximized (wall_dir, s)
end
```

**Comment by manilarome** [comment]
Thanks @AnthyG. Will close this now.

**Comment by animanoj** [comment]
@AnthyG 's solution worked, thanks!
