### ISSUE TITLE
[BUG - Including Fix][Linear]  Tooltip for wired network is broken

### ISSUE THREAD

**Issue by ryyzerr** [manilarome/the-glorious-dotfiles#145]
Theme:  Linear / Possibly Others
File:  `.config/awesome/widget/network/init.lua`

Issue:  There is a bug on line 321 which prevents the tooltip for wired networks from loading (it shows up blank)

Line 321 Broken:  `return 'Ethernet Interface: <b>' .. lan_interface`

Line 321 Fixed:  `return 'Ethernet Interface: <b>' .. lan_interface .. '</b>'`

**Comment by manilarome** [comment]
Thank you! Fixed it https://github.com/manilarome/the-glorious-dotfiles/commit/12b7b9e288ed975e935be39fdd7f142212589ed4
