### ISSUE TITLE
[FEATURE REQUEST][floppy] Entry in the wiki on how to change the clock type. (12h/24h)

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [manilarome/the-glorious-dotfiles#146]
Documentation : https://www.tcl.tk/man/tcl/TclCmd/clock.htm#M26
In order to change your clock from a 12 to a 24 hours clock.
Modify the `~/.config/awesome/layout/top-panel.lua` file, and search for `s.clock_widget = wibox.widget.textclock(` This line determine what to actually display in the clock designated space.
You can easily change the font, it´s size but also the clock format by replacing the previous `%l:%M %p` with `%k:%M`.
Legend : 
```
%l
    On output, produces a one- or two-digit number giving the hour of the day (12-11) on a 12-hour clock. On input, accepts such a number.
:
    Well, write :.
%M
    On output, produces the number of the minute of the hour (00-59) with exactly two digits. On input, accepts two digits and interprets them as the number of the minute of the hour.
%p
    On output, produces an indicator for the part of the day, AM or PM, appropriate to the given locale. If the script of the given locale supports multiple letterforms, lowercase is preferred. On input, matches the representation AM or PM in the given locale, in either case.
%k
    On output, produces a one- or two-digit number giving the hour of the day (0-23) on a 24-hour clock. On input, accepts such a number.```

**Comment by manilarome** [comment]
Thanks for the suggestion. FYI, you also use `man strftime` to see all the date and time syntax.

**Comment by manilarome** [comment]
[Done](https://github.com/manilarome/the-glorious-dotfiles/wiki/More)! Thanks for the suggestion!
