### ISSUE TITLE
[BUG] Dock position on second screen

### ISSUE THREAD

**Issue by Hkyx** [manilarome/the-glorious-dotfiles#147]
Hi @manilarome,

tried a second screen, and got a difference of the docker position, I started my config from linear which is bottom based for  the dock, but the second screen (differnet in resolution than the primary), display the dock on the top.

bottom-panel.lua:
```
	local panel_height = 32
    local fwidth = s.geometry.width
    local panel_w = s.geometry.width
	local panel_y = s.geometry.height - panel_height

	local panel = wibox
	{
		ontop = true,
		screen = s,
		type = 'dock',
		height = dpi(panel_height),
		width = panel_w,
        x = dpi(0),
		y = panel_y,
		bg = xr.color15,
		fg = xr.color0,
        border_width = dpi(0),
        border_color = xr.color12,
        shape = function(cr, w, h)
           gears.shape.rounded_rect(cr, w, h, dpi(0))
        end,
	}
```

I didn't touch anything on the init.lua in the parent folder so screens are still called in the same way.

do you get any idea? 

ty, hk

**Comment by manilarome** [comment]
So I installed arch in a virtual machine to test and debug multi-head setups. I can't seem to reproduced the issue here. Linear's bottom panel works fine to me.

![1123](https://user-images.githubusercontent.com/40349590/86893231-e2c0cb00-c133-11ea-9086-4c54507264ec.jpg)

**Comment by Hkyx** [comment]
mh, strange, don't get the same reasult on a new linear clone.
to get the full size dock on the both screen, I need to manage the size of the panel_width and still get a problem which is on the lower resolution, the dock still ne complete.

![screen_bug](https://user-images.githubusercontent.com/25575104/86926656-52b55e00-c100-11ea-8d83-2eac5f440ae0.png)

**Comment by manilarome** [comment]
Oh. What are your screen resolutions? Will try to debug it. Also, please try to use `dpi()` in your panel width.

**Comment by Hkyx** [comment]
Yeah I tried dpi(xx) to manager the extra size of the dock and it's the result ;p 

``` 
xrandr --output eDP1 --off --output DP1 --mode 1920x1080 --pos 2560x0 --rotate normal --output DP2 --primary --mode 2560x1440 -r 59.95 --pos 0x0 --rotate normal --output VIRTUAL1 --off'
```

**Comment by Hkyx** [comment]
don't know if it can help you, but I tried this awesome cfg to test and it's working for the dock size

https://github.com/Relz/awesome-wm-theme

**Comment by manilarome** [comment]
> don't know if it can help you, but I tried this awesome cfg to test and it's working for the dock size

The theme uses wibar instead of wibox. So try this:

```lua
	local panel = awful.wibar
	{
		ontop = true,
		screen = s,
		type = 'dock',
		height = dpi(panel_height),
		-- width = dpi(s.geometry.width),
		position = 'bottom',
		bg = beautiful.background,
		fg = beautiful.fg_normal
	}
```

**Comment by Hkyx** [comment]
tried, but it just remove the dock on all screens

**Comment by manilarome** [comment]
Oof I'm sorry. I don't really have an idea to fix this. Right now, I'm planning to rewrite these setups all over again from scratch. So I'll be focusing on that right now.

**Comment by Hkyx** [comment]
No worries :)
For your refactoring will you use the same code for all themes like modules, widgets... except personalization into each theme like for docks...?

**Comment by manilarome** [comment]
> will you use the same code for all themes like modules, widgets

Sort of? I think the right term should be refactor, not rewrite. My bad haha. Anyway, I will create a new branch and when I'm done with linear could you please test it on your multihead setup? I can't really figure out the problem because it works well in my multihead VM.

**Comment by Hkyx** [comment]
No problem rewrite is good too :)

mh, not sur how to explain it, but for example I think Elenapan use a way to avoid the duplication of the code in some part, widget use.... and put only what is needed into /theme/{theme1,theme2,theme3}  to get the needed customisation.

may be it's the wibox itself, I'm working with two usb3 hub to manage my two screen, can it be possible to get the problem from wibar? like lack of hardware managment  ?
But let me know I'll try :)

**Comment by manilarome** [comment]
> No problem rewrite is good too :)

Thanks!

> mh, not sur how to explain it, but for example I think Elenapan use a way to avoid the duplication of the code in some part, widget use.... and put only what is needed into /theme/{theme1,theme2,theme3} to get the needed customisation.

Yeah, elenapan's theme management/switching is the best implementation of it out there, but I don't really plan to add that feature right now because I want the setups to be completely separate from each other. And it's pretty easier to maintain(for me) haha. But yeah, code duplication is ugly.

> Can it be possible to get the problem from wibar? like lack of hardware managment ?

I'm not sure.

> But let me know I'll try :)

Thanks! It'll be a big help!
