### ISSUE TITLE
[QUESTION][TAG_TOGGLER] Have you ever thought of toggling your taglist? Especially in your linear setup. 

### ISSUE THREAD

**Issue by sauraveldho** [manilarome/the-glorious-dotfiles#148]
I love your work. Although I don't use these dotfiles as it is, I use your widgets and I learnt a lot from them.

But recently I'm curious about toggling the tag list. But I can't seem to do it.
Like when you hover over a circulat widget (in your bottom panel, linear setup) your taglist just extends out? Think it'll look very cool though.

And I usually use hotkeys to switch tags, so I also think it's a waste of space.

I'd prefer it as a feature for this, but you probably have things to do. If you could point me in the right direction, it'll help.

Thanks.

**Comment by manilarome** [comment]
I'm sorry but I don't plan to add/implement a toggler for taglist. You can create a button/keybind that will execute a callback that will hide it. The callback could be:

```lua
function()
    awful.screen.focused().bottom_panel.visible = not awful.screen.focused().bottom_panel.visible
end
```

That should toggle it on every click or keypress.
