### ISSUE TITLE
[BUG?][Surreal] Rofi not working

### ISSUE THREAD

**Issue by numine777** [manilarome/the-glorious-dotfiles#158]
First off, thanks a ton for doing all of this, the config is incredible.  

My system is a MacBook Pro Retina (set the DPI in ~/.Xresources to 155 for my choice of resolution) running Arch with your recommended and required dependencies installed.

The issue that I'm running into is that every time I try to launch rofi, I'm getting an error that "config.monitor=primary Could not find monitor"

I wouldn't normally open an issue, but I'm at my wit's end on this one.  Thanks in advance!

**Comment by NeoScaler** [comment]
Not really a solution, but I got this today when I tested my configuration using a Xephyr virtual display, but only there. As I logged in via display manager it worked.

**Comment by numine777** [comment]
Managed a fix.  Installed arandr, set the primary display and saved the shell script.  May have to run it on each setup, but it does let me use rofi now.

**Comment by manilarome** [comment]
Yep, you need to set your primary screen using `xrandr` or `arandr` at least once. But I think I'll just fix/rewrite the rofi. Closing this now! :)
