### ISSUE TITLE
[Question]The battey bad message occurred too frequently?

### ISSUE THREAD

**Issue by RMTT** [manilarome/the-glorious-dotfiles#161]
Seems when the battery status updated,the message will pop up,just several minutes.
May be we can show the message only once when start up : )

**Comment by manilarome** [comment]
What notification? Is it the *Battery is dead, literally*?

**Comment by RMTT** [comment]
> What notification? Is it the _Battery is dead, literally_?

yeah
![image](https://user-images.githubusercontent.com/20596599/88035251-72bf3580-cb74-11ea-9227-e9c2d38f7b3c.png)

**Comment by manilarome** [comment]
Please test https://github.com/manilarome/the-glorious-dotfiles/commit/0165a60dc03fbe3fb364e14964e25391761c8224

**Comment by RMTT** [comment]
> Please test [0165a60](https://github.com/manilarome/the-glorious-dotfiles/commit/0165a60dc03fbe3fb364e14964e25391761c8224)

seems ok

**Comment by manilarome** [comment]
Nice! But I feel like I will remove it in the future. I think it's annoying
if it popups every login/awesome restart. Also it will also show if your
laptop's battery health is 99% loo
