### ISSUE TITLE
[BUG][SURREAL] Error on startup 

### ISSUE THREAD

**Issue by tarunchhabriya06** [manilarome/the-glorious-dotfiles#162]
hello,
when I startup with surreal setup then the awesomeWM gives me this error

> Oops, there were errors during startup!
error while running function!
stack traceback:
	/home/tarun/.config/awesome/widget/dont-disturb/init.lua:150: in main chunk
	[C]: in function 'require'
	/home/tarun/.config/awesome/layout/control-center/init.lua:101: in main chunk
	[C]: in function 'require'
	/home/tarun/.config/awesome/layout/init.lua:4: in main chunk 
	[C]: in function 'require'
	/home/tarun/.config/awesome/rc.lua:20: in main chunk
error: /home/tarun/.config/awesome/widget/dont-disturb/init.lua:150: attempt to call a nil value (field 'connect_signal')

Hope someone can solve this error

**Comment by manilarome** [comment]
I can't somehow reproduced this. Did you change or modify anything? What's the output of `awesome --version`?

**Comment by tarunchhabriya06** [comment]
No didn't change anything 
and here is out of `awesome --version`

> awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**Comment by tarunchhabriya06** [comment]
Also, I am on manjaro with kernel version 5.4.44 and I am using lxde as a base

**Comment by manilarome** [comment]
> awesome v4.3 (Too long)

You're not using the git master branch. I reproduced this when I installed the stable build.
