### ISSUE TITLE
[BUG][Surreal] Attemp to compare nil value 

### ISSUE THREAD

**Issue by thangisme** [manilarome/the-glorious-dotfiles#163]
- Distro: Archlinux
 - Setup: Tested with Floppy and Surreal
 - Awesome Build: v4.3-858-g49a3859c8 (Too long)

I've installed everything using `yay -S the-glorious-dotfiles`. But I'm facing this issue when starting Awesome : 
[![https://imgur.com/Zxcjtbz.png](https://imgur.com/Zxcjtbz.png)](https://imgur.com/Zxcjtbz.png)
Nothing is clickable although the theme looks fine

**Comment by manilarome** [comment]
Make sure to have these `alsa-utils`, `pulseaudio`, `pulseaudio-alsa`.

**Comment by thangisme** [comment]
> Make sure to have these `alsa-utils`, `pulseaudio`, `pulseaudio-alsa`.

I just installed them but nothing changed

**Comment by manilarome** [comment]
I can't really reproduced this. Maybe try rebooting? Based on your log, you're also missing `mpc`. Please make sure to install the [optional dependencies](https://github.com/manilarome/the-glorious-dotfiles/wiki/Dependencies#optional-dependencies) to avoid this kind of errors. Things are `nil` or null  because the commands are missing hence no data to set in the sliders. Anyway, using `/root` for this is really a bad practice.

**Comment by thangisme** [comment]
After installing all optional dependencies, the issue hasn't gone
[![https://imgur.com/J4HYnP4.png](https://imgur.com/J4HYnP4.png)](https://imgur.com/J4HYnP4.png)
When pressed first icon in the lauch bar : 
[![https://imgur.com/a4qsjkG.png](https://imgur.com/a4qsjkG.png)](https://imgur.com/a4qsjkG.png)

**Comment by manilarome** [comment]
> No backlight controller was found

That is the reason you're having this errors about the volume slider. What about the volume? Do you have an audio device?  Is it running? Are drivers installed, perhaps?

>  When pressed first icon in the lauch bar :

It's in the [wiki](https://github.com/manilarome/the-glorious-dotfiles/wiki/). Specifically this [section](https://github.com/manilarome/the-glorious-dotfiles/wiki/How-Tos#fix-rofi-not-launching-and-error). You need to set your primary display either using arandr or xrandr.

**Comment by thangisme** [comment]
What if I don't have audio device? Can I manually remove volumn slider widget?

**Comment by manilarome** [comment]
Yep! It depends on the setup tho. You can just comment them out. You can look inside the `awesome/layout` directory. If you're using Surreal it's in here https://github.com/manilarome/the-glorious-dotfiles/blob/8a364aaf5658eb1e8ed2f01e8890d3bb614fa9ef/config/awesome/surreal/layout/control-center/init.lua#L134-L140

**Comment by thangisme** [comment]
Is there any Awesomewm's log file? I'm using VNC to remote access. There's no error in VNC log file but I can't start application, App menu even doesn't show up application's icons

**Comment by manilarome** [comment]
> Is there any Awesomewm's log file?

Yes you can find it in your `xsession-logs`. 

> I'm using VNC to remote access

I don't know how VNC works and never tried it so I don't know if there's a log for awesomewm there.

> App menu even doesn't show up application's icons

You can change/set the icon theme by opening `awesome/theme/default-theme.lua` and setting the value of `theme.icon_theme` to your desired one.

**Comment by thangisme** [comment]
I can't see any xsession-logs file. 
Is the following error a AwesomeWM issue or it cause by the theme? 
[![https://imgur.com/h9dhccI.png](https://imgur.com/h9dhccI.png)](https://imgur.com/h9dhccI.png)
