### ISSUE TITLE
[Suggestion] Add 'copyq' to dialog rules

### ISSUE THREAD

**Issue by jbsilva** [manilarome/the-glorious-dotfiles#164]
https://github.com/manilarome/the-glorious-dotfiles/blob/8a364aaf5658eb1e8ed2f01e8890d3bb614fa9ef/config/awesome/floppy/configuration/client/rules.lua#L41

CopyQ is a clipboard management that opens a dialog to chose what to paste.
The class is 'copyq'.

**Comment by manilarome** [comment]
Nope, sorry. The default configurations of the setups are my personal configurations tbh. So I'm not really planning to add it because I don't use it. You're free to add it on your rules tho.
