### ISSUE TITLE
[Question] configure monitors at startup

### ISSUE THREAD

**Issue by jbsilva** [manilarome/the-glorious-dotfiles#165]
The following is my .xinitrc:
```
[ -f ~/.xprofile ] && . ~/.xprofile
xrandr --output eDP1 --off --output HDMI1 --mode 1920x1080
exec awesome
```
For some reason, the xrandr line is not working (even after `exec awesome`).
What I'm doing now is waiting awesome to load, running this line in a terminal and then restarting awesome.

Do you know how to do this configuration automatically at startup? The .xinitrc used to work with the default awesome config.

**Comment by manilarome** [comment]
Don't have an idea, but a quick search on google I found this https://unix.stackexchange.com/questions/125556/how-can-i-make-xrandr-changes-persist
