### ISSUE TITLE
[Question] The Wifi widget shows no connection, even if I'm connected to a wifi network

### ISSUE THREAD

**Issue by rizwan2000rm** [manilarome/the-glorious-dotfiles#169]
First of all I really love your work thanks for the configs, learned alot from it.

The wifi widget doesn't seem to work on my laptop for some reason, I have nm-applet installed so it shows that I'm connected to a wifi network but the widget from the config doesn't.

Do I have to configure something for the widget to work ?
![20200805_080702](https://user-images.githubusercontent.com/48753482/89345768-9b434580-d6c5-11ea-86f4-0921dc088806.png)

**Comment by manilarome** [comment]
You need to change the interface. Open awesome/widget/init.lua and change
the lan and wlan interface with yours.

**Comment by rizwan2000rm** [comment]
Thanks got it working.
Yeah it would be nice to have everything that needs to be configured in a separate file or directory for beginners. Or maybe add it to How to's section of readme.

**Comment by manilarome** [comment]
No problem! Yeah! I'm just cleaning things up before adding a configuration file. Thanks for your kind words! Closing this now.
