### ISSUE TITLE
[BUG] [ALL] Lockscreen Module - lua-pam library breakage on lua5.4 if compiled on 5.3

### ISSUE THREAD

**Issue by manilarome** [manilarome/the-glorious-dotfiles#172]
**Technical Information (please complete the following information):**
 - Distro:  Archlinux
 - Setup: All
 - Awesome Build:
     - awesome v4.3-862-g7a759432d (Too long)
      • Compiled against Lua 5.3.5 (running with Lua 5.3)
      • API level: 4
      • D-Bus support: yes
      • xcb-errors support: no
      • execinfo support: yes
      • xcb-randr version: 1.6
      • LGI version: 0.9.2
      • Transparency enabled: yes
      • Custom search paths: no

**Describe the bug**
Breakage on `lua 5.4` if compiled on `5.3`.
![image](https://user-images.githubusercontent.com/40349590/89502851-389e9680-d7f8-11ea-95f9-4b319d6c60a8.png)

**To Reproduce**
1. Lockscreen
2. Try to authenticate
3. Lockscreen crashed (stops keygrabbing) . Use <kbd>super + ctrl + r </kbd> to unlock.

**Expected behavior**
Working

**Additional context**
AwesomeWM runs and was compiled using lua53. And 5.4 is currently unsupported. So using the lua-pam causes this issue. 

```
2020-08-06 15:17:03 E: awesome: Error during a protected call: version mismatch: app. needs 504.0, Lua core provides 503.0
```

**Comment by manilarome** [comment]
@RMTT is there a way to build the lua-pam library with a certain lua version like `5.3`? Currently, AwesomeWM does not support `5.4` so compiling the lib on top of 5.4 breaks it if used on awesomewm. I'm just really noob at this.

**Comment by RMTT** [comment]
> @RMTT is there a way to build the lua-pam library with a certain lua version like `5.3`? Currently, AwesomeWM does not support `5.4` so compiling the lib on top of 5.4 breaks it if used on awesomewm. I'm just really noob at this.

off course, just modify the `CMakeLists.txt` to specific the lib file and include directory

**Comment by manilarome** [comment]
I see! Thanks will look into it!

**Comment by manilarome** [comment]
So I tried the snippet below, but the package was still compiled on top of `5.4`.  Can you please enlighten me here?

```
cmake_minimum_required(VERSION 3.15)
project(lua_pam)

include_directories(/usr/lib/s)

set(CMAKE_CXX_STANDARD 14)
set(SOURCE_DIR src)

add_library(lua_pam SHARED ${SOURCE_DIR}/main.cpp)
target_link_libraries(lua_pam lua5.3 pam)
```

**Comment by RMTT** [comment]
> So I tried the snippet below, but the package was still compiled on top of `5.4`. Can you please enlighten me here?
> 
> ```
> cmake_minimum_required(VERSION 3.15)
> project(lua_pam)
> 
> include_directories(/usr/lib/)
> 
> set(CMAKE_CXX_STANDARD 14)
> set(SOURCE_DIR src)
> 
> add_library(lua_pam SHARED ${SOURCE_DIR}/main.cpp)
> target_link_libraries(lua_pam lua5.3 pam)
> ```

```lua
 cmake_minimum_required(VERSION 3.15)
 project(lua_pam)
 
 set(CMAKE_CXX_STANDARD 14)
 
 set(SOURCE_DIR src)
 include_directories(/usr/include/lua5.3)
  
 add_library(lua_pam SHARED ${SOURCE_DIR}/main.cpp)
 target_link_libraries(lua_pam lua5.3 pam)
```
try this, but you need install `lua5.3` by `pacman -S lua53`

**Comment by manilarome** [comment]
Yeah it works! Thanks a lot!
