### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WilliamOtieno** [manilarome/the-glorious-dotfiles#174]
**Technical Information (please complete the following information):**
 - Distro: Arch Linux
 - Setup: Floppy
 - Awesome Build: 4.3
**Describe the bug**
I have lua5.3 and 5.4 installed in my system yet when I reload awesome, it crushes with errors relating to failing to load the required files in /usr/share/lua.....etc

```
error while running function!
stack traceback:
    [C]: in function 'require'
    ...e/william/.config/awesome/configuration/client/rules.lua:3: in  main chunk
error:...e//william/.config/awesome/configuration/client/rules.lua:3: module 'ruled' not found:
    no field package.preload['ruled']
    no file '/usr/share/lua/5.3/ruled.lua'
    no file '/etc/xdg/awesome/ruled.lua'
```
This is only a gist of the error

**Comment by manilarome** [comment]
Sorry it's not a bug. You're using the stable version of awesome. Please, use the latest awesome-git master branch.
