### ISSUE TITLE
[Question] Battery, and wifi in the bottom panel do not work in Gnawesome

### ISSUE THREAD

**Issue by IgnisDa** [manilarome/the-glorious-dotfiles#175]
I have been trying to setup your Gnawesome layout, and did it after some time. Howver, the wifi and the battery icons in the bottom right do not work. I am on Manjaro (i3 edition).
The wifi icon says I am disconnected even though I am not (I am writing this question from my laptop), while the Battery icon is indefinitely stuck at 100% even though it is disconnected from the power socket.

![error2](https://user-images.githubusercontent.com/60938164/89711927-f2d5ff80-d9aa-11ea-9b7b-a2b0aab8d604.png)

Additionally, I keep getting this notification: 
![error](https://user-images.githubusercontent.com/60938164/89711923-ed78b500-d9aa-11ea-9734-8cb1af48b12b.png)

I have tried to debug these issues, but I don't know lua and couldn't find a similar issue from the internet. 
Any help would be appreciated!

PS: I would also appreciate if you give me pointers as to how to change the icons on the bottom left. I use google-chrome but the default seems to be firefox.
![erroe3](https://user-images.githubusercontent.com/60938164/89712148-9a9ffd00-d9ac-11ea-961c-594a4962a1f4.png)

Nice rice btw.

**Comment by manilarome** [comment]
> Howver, the wifi and the battery icons in the bottom right do not work. I am on Manjaro (i3 edition).

Read https://github.com/manilarome/the-glorious-dotfiles/issues/169

> while the Battery icon is indefinitely stuck at 100% even though it is disconnected from the power socket.

What's the output of `upower -i $(upower -e | grep BAT) | grep percentage | awk '{print $2}' | tr -d '\n%'`? Also make sure you have upower installed. Check the wiki for complete dependencies.

**Comment by IgnisDa** [comment]
I found the name of my interface through `iw dev`, and it's called `wlo1`. In `~/.config/awesome/widget/network/init.lua`, this is what I put:
```
-- Configuration
local interfaces = {
	wlan_interface = 'wlo1',
	lan_interface = 'enp0s25'  -- My laptop doesn't have lan
}
```
It still doesn't work.
> What's the output of upower -i $(upower -e | grep BAT) | grep percentage | awk '{print $2}' | tr -d '\n%'? Also make sure you have upower installed. Check the wiki for complete dependencies.

It shows `96`, so it looks fine. But the battery widget still doesn't work.

**Comment by manilarome** [comment]
> PS: I use the fish shell, and the syntax is a bit different. Does it matter?

Yes! The syntax matters. There's someone posted the same problem like yours and it turns out that he uses `fish`. `xsession-error` would also be helpful.

**Comment by manilarome** [comment]
So I switched to `fish` and it broke everything. ~~I'll just make everything POSIX compliant for compatibility.~~ Oof it turns out fish isn't and never tried to be compatible with POSIX sh.

**Comment by manilarome** [comment]
> PS: I would also appreciate if you give me pointers as to how to change the icons on the bottom left. I use google-chrome but the default seems to be firefox.

All the icons are in `awesome/config/themes/icons/` but the taglist's icons are in the `tag-list` folder inside the said path.

**Comment by IgnisDa** [comment]
> So I switched to fish and it broke everything. I'll just make everything POSIX compliant for compatibility. Oof it turns out fish isn't and never tried to be compatible with POSIX sh.

Does that mean I won't be able to get things working without changing back to `fish` or `zsh`? Bummer...

> All the icons are in awesome/config/themes/icons/ but the taglist's icons are in the tag-list folder inside the said path.

Thanks for this!

**Comment by manilarome** [comment]
> Does that mean I won't be able to get things working without changing back to bash or zsh? Bummer...

Uhm, yeah looks like it. Don't know a lot about fish and supporting it will be a lot of work (maybe not, I just don't get the fish's syntaxes right now).

> Thanks for this!

no problem

**Comment by manilarome** [comment]
I managed to make it work by escaping `$`. Of course just escaping all of it will not fix all the issues. Anyway, I'll do my best to support fish because it's a pretty good shell when I tried it.

**Comment by IgnisDa** [comment]
Do you mean escaping `$` or completely removing it altogether? Because if you type `echo $(du -h . | tail)` (or any other command in fact), you'll get an error. The correct syntax is `echo (du -h . |tail)`.

> it's a pretty good shell when I tried it.

Yeah it's absolutely awesome, especially with the oh-my-fish plugins.

**Comment by manilarome** [comment]
> Do you mean escaping $ or completely removing it altogether? 

Nope but by enclosing it with `sh` or `bash`. `sh -c  "echo \$(du -h  | tail)"`

> Yeah it's absolutely awesome, especially with the oh-my-fish plugins.

I see. Will definitely check it out.
