### ISSUE TITLE
[QUESTION] I have issues with application launcher...

### ISSUE THREAD

**Issue by G10by** [manilarome/the-glorious-dotfiles#176]
The issue is simple when i press `[mod] + [shift] + r ` i got this error `The configuration failed to validate config.monitor=primary Could not find monitor Please update your configuration` is there any solution and also if its possible to remove tittle bar , Im really noob into WM awesome is my first one and all i can just say is that I love your work

**Comment by manilarome** [comment]
Please follow the format next time.

> The configuration failed to validate config.monitor=primary Could not find monitor Please update your configuration

Read https://github.com/manilarome/the-glorious-dotfiles/wiki/How-Tos#fix-rofi-not-launching-and-error

> remove tittle bar

Comment/remove the titlebar module in `rc.lua`.
