### ISSUE TITLE
[Question] How to change tasks icons?

### ISSUE THREAD

**Issue by Ryunaq** [manilarome/the-glorious-dotfiles#179]
How to change the tasks icons? I already modified `default-theme.lua` but it doesn't seem to be affecting it. Lxappearance and qt5c are already configured but no change.

I am sorry for making this question here but I've read all the program and searched online and couldn't find the answer.

**Comment by manilarome** [comment]
You can change the icons in `awesome/themes/icons/tag-list`.

**Comment by Ryunaq** [comment]
Hey thanks for answering, sorry for bothering again but I meant the *tasks*, not the tags.

**Comment by manilarome** [comment]
Oof I'm sorry. Just got woke up so my mind's still wonky. Anyway, I can change its icon's theme using `lxappearance`. Try to also reproduce it on a vanilla `rc.lua`, if the problem persists, consider submitting an issue on awesomewm repo.

**Comment by Ryunaq** [comment]
Np! That's the weirdest thing, `lxappearance` is setted correctly, I can tell because the `rofi_appmenu` works with the correct icons. I thought the `rc.lua` configured those fonts but I guess it doesn't, just copied the clean awesome config and the problem persists. So this problem isn't really relevant to this git. Thanks for your help!
