### ISSUE TITLE
[BUG] Boolean configuration doesn’t work

### ISSUE THREAD

**Issue by tiosgz** [manilarome/the-glorious-dotfiles#182]
…if the default is `true` & you solve missing config by `var = config.bla.bla or true`, coz `false or true` is `true`.

If you still need the info…

**Technical Information (please complete the following information):**
 - Distro: Artix Linux
 - Setup: Custom, only copied the lock screen & what I needed to make it work
 - Awesome Build: v4.3-862-g7a759432d-dirty (Too long)

**Describe the bug**
Please see above.

**To Reproduce**
Example steps to reproduce the behavior:
1. Change `config.module.lockscreen.blur_background` to `false`
2. Restart Awesome
3. Lock screen
4. The background is still blurred

**Expected behavior**
The config should respect my preference, i.e. in this case the background should not be blurred.

**Screenshots**
Not needed, I think.

**Additional context**
Well, do you need to know more?

**Comment by manilarome** [comment]
Ah yes. My bad. Will change the default value to false then.

**Comment by manilarome** [comment]
https://github.com/manilarome/the-glorious-dotfiles/commit/958d187a261ca5fbb7762aa7c039ddc7f6d2b5b3 will solve this. Anyway, thanks for reporting! Closing this now.
