### ISSUE TITLE
[Feature Request] Showcase video?

### ISSUE THREAD

**Issue by SmartBoy84** [manilarome/the-glorious-dotfiles#187]
It would be great if you could make a simple video of all the setups in action!

**Comment by manilarome** [comment]
Sorry, but I don't plan to make a showcase video. I only have a Lenovo x230, so recording is a pain. It causes overheating and extreme lag. Also add the artifacts produced by picom (with dual-kawase blur on while recording). So yeah, the [gif](https://raw.githubusercontent.com/manilarome/the-glorious-screenshots/master/glorious.gif) is the only thing I could provide right now for showcasing the setups.

**Comment by SmartBoy84** [comment]
External camera?
