### ISSUE TITLE
[Feature Request] Make tags/init.lua use default_app defined in apps.lua

### ISSUE THREAD

**Issue by LocutusDeBorg** [manilarome/the-glorious-dotfiles#189]
Right now, tags/init.lua have default_app hard coded.  When a user wants to change a default app for a tag, they must change app.lua and tags/init.lua

I request that tags/init.lua use the same application defined in apps.lua.
For example, the begining of tags/init.lua could change from: 

```
local icons = require('theme.icons')

local tags = {
	{
		type = 'terminal',
		icon = icons.terminal,
		default_app = 'kitty',
		gap = beautiful.useless_gap,
		layout = awful.layout.suit.floating
	},

```
to: 
```
local icons = require('theme.icons')
local apps = require('configuration.apps')

local tags = {
	{
		type = 'terminal',
		icon = icons.terminal,
		default_app = apps.default.terminal,
		gap = beautiful.useless_gap,
		layout = awful.layout.suit.floating
	},

```

**Comment by manilarome** [comment]
Hmm yeah that would be a nice addition. Thanks for the suggestion!

**Comment by manilarome** [comment]
https://github.com/manilarome/the-glorious-dotfiles/commit/e8b92170d8440df82ab84e05e4077b615f9380ad
