### ISSUE TITLE
[BUG] Toggle fullscreen + Increase/decrease master width factor not working

### ISSUE THREAD

**Issue by S1ngl3-x** [manilarome/the-glorious-dotfiles#190]
**Technical Information (please complete the following information):**
 - Distro: Manjaro
 - Setup: Surreal (but I think Alll)
 - Awesome Build: 4.3.886

**Describe the bug**
It is impossible to change the width factor of a window. For example make one terminal take up 2/3 of horizontal space.
Also I can not set window to fullscreen.
Both of them just don't react at all.

**To Reproduce**
1. Clone repo, copy config/awesome/sureal as $USER/.config/awesome 
2. Realod awesome
3. Open two terminals, try to adjust width or set fullscreen.
4. Nothing happens.

**Expected behavior**
Master resizing should work as in "config less" awesome and fullscreen as well.

(It may be possible I am just missing something though.)

**Comment by manilarome** [comment]
This is not a bug.

> Master resizing should work as in "config less" awesome

Master resizing doesn't work on dwindle layout. Using tiling instead.

![image](https://user-images.githubusercontent.com/40349590/95269368-d6035e80-086b-11eb-9974-bc4b4ed4d7da.png)

> fullscreen as well

Works fine to me.

![image](https://user-images.githubusercontent.com/40349590/95269432-f3382d00-086b-11eb-91c5-b4f88efa7fc5.png)

**Comment by S1ngl3-x** [comment]
Thank you for the dwindle tip. Tiling and width resizing is working fine (but I liked dwindle more :( ).
However the fullscreen just isn't working for me. I pulled to repo to make sure I am not missing anything, but to no avail. I even checked that mod4 + "f" is fullscreen.
Is there some way to debug this?
Thank you

**Comment by manilarome** [comment]
> but I liked dwindle more

Same. It makes sense tho that you can't change its master width lol.

> the fullscreen just isn't working for me

Define "not working". Is the keybind for it </kbd> super + f</kbd> doesn't work (for a certain client or all of it)? 

>  Is there some way to debug this?

For starters, you can check `~/.xsession-errors`. You can also test by using the vanilla rc.lua. Check if it's reproducible. (Can't really reproduce this on my end)

**Comment by S1ngl3-x** [comment]
> Same. It makes sense tho that you can't change its master width lol.
> 
Yeah, it does, unfortunately :( 

> Define "not working". Is the keybind for it - super + f, doesn't work (for a certain client or all of it)?
> 
Nothing happens when I click super + f and I made sure the shortcut is defined in client/keys.lua. Entering full screen by other means works, for example VLC fullscreen, YouTube fullscreen and so on.
Other shortcuts in keys.lua work normally.

> For starters, you can check `~/.xsession-errors`. You can also test by using the vanilla rc.lua. Check if it's reproducible. (Can't really reproduce this on my end)
I have found the issue. It is just the mod 'f' combination that is not working for me.
I changed it to mod F11 and it works. I have no idea, what is the problem. I am 100% sure that there is no conflicting shortcut. I even removed all of my lines that contained 'f' or "f" . 
I guess I will just live now wit the new shortcut.

Also no sing of relevant error or warning in logs

`/etc/profile.d/perlbin.sh: line 5: append_path: command not found
/etc/profile.d/perlbin.sh: line 7: append_path: command not found
/etc/profile.d/perlbin.sh: line 9: append_path: command not found
WARNING: modelines must use ASCII
2020-10-07 13:50:17 W: awesome: a_glib_poll:470: Last main loop iteration took 0.530812 seconds! Increasing limit for this warning to that value.
2020-10-07 13:50:18 W: awesome: spawn_child_exited:388: Unknown child 113068 exited with status 0
No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.

No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.

2020-10-07 13:50:18 E: awesome: Error during a protected call: ...e/adam/.config/awesome/widget/temperature-meter/init.lua:91: attempt to perform arithmetic on a nil value (local 'temp')
stack traceback:
	...e/adam/.config/awesome/widget/temperature-meter/init.lua:91: in upvalue 'callback'
	/usr/share/awesome/lib/awful/widget/watch.lua:78: in function </usr/share/awesome/lib/awful/widget/watch.lua:77>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:487: in function </usr/share/awesome/lib/awful/spawn.lua:481>
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
	/usr/share/awesome/lib/awful/spawn.lua:601: in function </usr/share/awesome/lib/awful/spawn.lua:593>
MPD error: Connection refused
`

I think this is a bug, but I can not pin point and issue. And if I am the only one affected, then I guess just let's ignore it.

Thank you for your help, your config is awesome-glorious!
Bye

**Comment by manilarome** [comment]
> I have found the issue. It is just the mod 'f' combination that is not working for me.
I changed it to mod F11 and it works. I have no idea what is the problem. I am 100% sure that there is no conflicting shortcut. I even removed all of my lines that contained 'f' or "f" .

Yeah. That's weird. Also, double check if you have a settings daemon running like `xfsettingsd`. Sometimes, this process tends to "steal" the shortcut keys and cause problems like this.

> 2020-10-07 13:50:18 E: awesome: Error during a protected call: ...e/adam/.config/awesome/widget/temperature-meter/init.lua:91: attempt to perform arithmetic on a nil value (local 'temp')
stack traceback:
...e/adam/.config/awesome/widget/temperature-meter/init.lua:91: in upvalue 'callback'
/usr/share/awesome/lib/awful/widget/watch.lua:78: in function </usr/share/awesome/lib/awful/widget/watch.lua:77>
(...tail calls...)
/usr/share/awesome/lib/awful/spawn.lua:487: in function </usr/share/awesome/lib/awful/spawn.lua:481>
[C]: in function 'xpcall'
/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
(...tail calls...)
/usr/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
/usr/share/awesome/lib/awful/spawn.lua:601: in function </usr/share/awesome/lib/awful/spawn.lua:593>
MPD error: Connection refused

These are definitely from awesomewm's stderr. But yeah these are not relevant to the problem.

> I think this is a bug but I can not pin point the exact issue and the cause of it. And if I am the only one affected then I guess just let's ignore it.

Yeah, hopefully you can find the culprit and fix it.

And thank you and you're welcome. Appreciate it.
