### ISSUE TITLE
Module required ruled, loading into default awesome WM

### ISSUE THREAD

**Issue by HarryBurge** [manilarome/the-glorious-dotfiles#192]
New to Arch Linux, I have downloaded all the dependences, and done the install process. I am using
`xinit awesome` 
To start.
However getting this error, might be something stupid due to being new.
![16029641283644697784958145381729](https://user-images.githubusercontent.com/40576217/96352309-325f4d00-10ba-11eb-9079-630c1d1eb0f7.jpg)

Thanks for your help :)

**Comment by manilarome** [comment]
Ruled library is missing. Please use the awesome-git version. You can install it from AUR.

**Comment by HarryBurge** [comment]
Did as said, getting an error from xterm on
`xinit awesome-git`
![16030365911775928930277051769816](https://user-images.githubusercontent.com/40576217/96373217-eddbbc00-1162-11eb-82d3-ad480dcc33c0.jpg)
I know its not your package but would you happen to know the problem?

**Comment by manilarome** [comment]
`awesome-git` is just a name of the package. The binary's name still just `awesome`. You can get its path by `$ which awesome`.

**Comment by HarryBurge** [comment]
Thank you, this is working now
