### ISSUE TITLE
[BUG] Can't open application drawer

### ISSUE THREAD

**Issue by xVyre** [manilarome/the-glorious-dotfiles#194]
**Technical Information (please complete the following information):**
 - Distro: Ubuntu 20.04 LTS
 - Setup: Floppy
 - Awesome Build: awesome v4.3-894-gcc67a5b4 (Too long)

**Describe the bug**
When trying to open the application drawer, I get the following error:
Error while parsing theme: /home/vr/.config/awesome//configuration/rofi/appmenu/rofi.rasi
     Parser error: syntax error, unexpected invalid property value, expecting "property close(';')"
     Location: line 80 column 13 to line 80 column 25
     File       '/home/vr/.config/awesome/configuration/rofi/appmenu/rofi.rasi'

**To Reproduce**
1. Click on the icon in the top left (or press Super+e)
2. See error

**Expected behavior**
The application drawer opens

**Screenshots**
*I would but apparently I can't while that error is open lol*

**Comment by manilarome** [comment]
Did you modify it? Line 80 has semicolon: https://github.com/manilarome/the-glorious-dotfiles/blob/c2c618563221bf3f7eec164b7b842de2934831ea/config/awesome/floppy/configuration/rofi/appmenu/rofi.rasi#L80. Also, check your rofi version, latest stable version of rofi is required.

**Comment by xVyre** [comment]
The file was unmodified but it turns out I was on rofi 1.5.4 and not 1.5.4-dev. I built the new version and it works fine now, thanks!
