### ISSUE TITLE
[BUG] Wifi widget not updating

### ISSUE THREAD

**Issue by xVyre** [manilarome/the-glorious-dotfiles#195]
**Technical Information (please complete the following information):**
 - Distro: Ubuntu 20.04 LTS
 - Setup: Floppy
 - Awesome Build: awesome v4.3-894-gcc67a5b4 (Too long)

**Describe the bug**
I'm connected to the internet but the wifi icon still shows as disconnected, and when I hover over it it stays "Loading..."

**To Reproduce**
1. Log in
2. Wait a few seconds
3. See how the icon never updates

**Expected behavior**
The icon updates and shows wifi strength.

**Additional context**
- Yes, I set the wireless interface to the right one (wlp2s0)
- I am using wpa_supplicant, not iwd although I don't think that's relevant
- I went through `widget/network/init.lua` and manually did all the "tests" myself, e.g `iw dev wlp2s0 link` and the different bash scripts, and everything came out as intended so I don't see why it's not updating
- I tried changing the timeout for network_updater to see if it would help but nothing changed

**Comment by manilarome** [comment]
You can check this inline script if it works: https://github.com/manilarome/the-glorious-dotfiles/blob/c2c618563221bf3f7eec164b7b842de2934831ea/config/awesome/floppy/widget/network/init.lua#L288-L330

The script reads `/sys/class/net/INTERFACE/operstate` to check if the interface is connected to the internet or not. So the culprit to your problem is probably here. I don't currently use awesomewm right now, so I cannot test it. Good luck!

**Comment by xVyre** [comment]
Thanks for the input. I figured out it was zsh that was causing this, and I didn't want to change my shell so I just copied the bash script and put it into a file in `widget/network`:
![image](https://user-images.githubusercontent.com/38956768/98084896-f25be080-1e95-11eb-9e0f-22c00e927f3f.png)

I then changed the function to look like:
![image](https://user-images.githubusercontent.com/38956768/98085010-259e6f80-1e96-11eb-88b9-213c395eca51.png)

Restarted awesome, still no luck :/ I don't really know lua at all, so I was wondering if you had any ideas? Maybe some way to check if it's spitting out any errors anywhere?

**Comment by manilarome** [comment]
> I figured out it was zsh that was causing this

This shouldn't have happened. https://github.com/manilarome/the-glorious-dotfiles/blob/c2c618563221bf3f7eec164b7b842de2934831ea/config/awesome/floppy/rc.lua#L15 This line should set the default shell of awesome to `sh`.

> Maybe some way to check if it's spitting out any errors anywhere?

Add a second parameter to the callback of `check_network_mode()`'s `awful.spawn.easy_async_with_shell`. This should return an error if there's any. Use `naughty` or something to print/see the output.

**Comment by xVyre** [comment]
Mistake number 1: ./test.sh was an obvious mistake on my part, oops lol
So after I correctly referenced the script I got a bunch of sh syntax errors so I just changed awful.util.shell to bash. Everything's fine now, thanks for all the help!
