### ISSUE TITLE
[BUG] Transparent/blurred windows not working

### ISSUE THREAD

**Issue by xVyre** [manilarome/the-glorious-dotfiles#198]
**Technical Information (please complete the following information):**
 - Distro: Ubuntu 20.04 LTS
 - Setup: Floppy
 - Awesome Build: awesome v4.3-894-gcc67a5b4 (Too long)

**Describe the bug**
Everything was working fine until a couple of days ago (specifically after I got your blurredfox extension but removing it didn't fix anything so I don't think it's related) Any windows that are supposed to have transparent/blurred backgrounds now have black ones. Also, I'm not sure if this is related but since then neither the Today bar nor the dashboard are opening on top of the screen, instead they open but the rest of the screen "disappears".

**To Reproduce**
1. Log in
2. Look at anything that's supposed to be transparent (e.g. kitty or Thunderbird with thunderblurred extension)
3. See how it's black

**Expected behavior**
The windows/apps should have a transparent background

**Screenshots**
![image](https://user-images.githubusercontent.com/38956768/98468721-397b0600-21f5-11eb-8a6c-a014782fe80c.png)
kitty
![image](https://user-images.githubusercontent.com/38956768/98468747-4e579980-21f5-11eb-97a4-b7949462bf5e.png)
Firefox with blurredfox
![image](https://user-images.githubusercontent.com/38956768/98468772-6deec200-21f5-11eb-8820-e476ac3b1331.png)
Dashboard not overlapping

**Additional context**

- I compared my picom.conf to the one in the repo just in case I messed something up, but they're the same
- I even tried switching to tryone144's fork of picom (specifically the feature/dual_kawase branch) but I still got the same issue
- My picom version is vgit-5e021

Could you maybe give me a specific version of picom that you used that is sure to work?

**Comment by manilarome** [comment]
It's "black" because the compositor is not running. You can manually start picom from your terminal (make sure to use the config of the setup).

> Could you maybe give me a specific version of picom that you used that is sure to work?

I always use the git master branch. But right now, I don't use awesome anymore, so is picom. Try to downgrade your picom if it's working before. Maybe it's an upstream problem (picom).
