### ISSUE TITLE
[Feature Request] Pywal support

### ISSUE THREAD

**Issue by Cyliann** [manilarome/the-glorious-dotfiles#199]
It would be awesome if this dotfiles were supported by pywal. Unfortunatly whenever I change color scheme using pywal, the scheme comes back to original as soon as I open terminal. I'm new to awesome wm, so I'm not able to make a PR.

**Comment by manilarome** [comment]
Sorry but I have to reject this. I don't really use pywal and not using awesome anymore (right now). So yeah closing this now. Thanks for the suggestion!
