### ISSUE TITLE
[GNawesOME] Attempt to index nil value top_panel (problems on a multi-monitor setup)

### ISSUE THREAD

**Issue by pucilpet** [manilarome/the-glorious-dotfiles#27]
I have this error on the GNawesOME:

/.config/awesome/layout/init.lua:26: attempt to index a nil value (field 'top_panel')

I managed to fix it by adding a few lines of code.

`if s.top_panel then
...
end`

to...

`-- Hide bars when app go fullscreen
function updateBarsVisibility()
  for s in screen do
    if s.selected_tag then
      local fullscreen = s.selected_tag.fullscreenMode
      -- Order matter here for shadow
      s.bottom_panel.visible = not fullscreen
      if s.top_panel then
      s.top_panel.visible = not fullscreen
      end
    end
  end
end
`

---
Also some other errors on multi-screen setup, I noticed mini-settings menu opens on screen 2 even though I try to open it on screen 1. I had some similar errors on Floppy too with widgets opening on the 2nd screen. :)

**Comment by manilarome** [comment]
I'm rewriting the floppy setup and it already supports multimonitor setup and fixed all the major bugs. However, it's not finish yet. And I'm considering dropping the other setups, because maintaining four of them is troublesome. 

> Also some other errors on multi-screen setup, I noticed mini-settings menu opens on screen 2 even though I try to open it on screen 1. I had some similar errors on Floppy too with widgets opening on the 2nd screen. :)

To fix that you need to add `screen.geometry.x` in your wibox's **x**.
Example:
```lua
local right_panel = function(screen)

	-- Set right panel geometry
	local panel_width = dpi(350)
	local panel_x = screen.geometry.x + screen.geometry.width - panel_width

	local panel = wibox {
		ontop = true,
		screen = screen,
		type = 'dock',
		width = panel_width,
		height = screen.geometry.height,
		x = panel_x,
		y = screen.geometry.y,
		bg = beautiful.background,
		fg = beautiful.fg_normal
	}
...
```

**Comment by ildar** [comment]
I'm sorry is there a ETA? I'm having this issue annoying me constantly.

**Comment by manilarome** [comment]
@ildar  Uhm.. maybe it'll take 1-2 weeks. I already finished fixing some of the major bugs and already added support for multihead setup for `floppy`. So applying these fixes to `lines`, `rounded` and `gnawesome` will take some time haha.

**Comment by ildar** [comment]
BTW thanks for this. Really eye-candy setup for Awesome!

**Comment by manilarome** [comment]
Hello @pucilpet, GNawesOME has been updated and this problem has already been fixed!
