### ISSUE TITLE
[GNawesOME] bottom dock size should be calculated

### ISSUE THREAD

**Issue by ildar** [manilarome/the-glorious-dotfiles#30]
I decreased the tags count and see the dark dock is larger then its contents.

**Comment by manilarome** [comment]
You can try changing the `wibox` to `awful.popup`. `awful.pop`up' size is based on its content so that will satisfy your needs

**Comment by ildar** [comment]
GNawesOME EOL?

**Comment by manilarome** [comment]
Nope. I'm planning to rewrite it to fix some design flaws. The only setup I
considered dropping is `lines` because it's just `rounded` but with lines.
Haha

**Comment by manilarome** [comment]
Hello, the GNawesOME has been rewritten! And I implemented  your suggestion here! Thanks!

**Comment by ildar** [comment]
Right! closing.
Will file a new issue for that :-)
