### ISSUE TITLE
Can't use xdg-folders widget

### ISSUE THREAD

**Issue by ShadowProgr** [manilarome/the-glorious-dotfiles#34]
I can't open the shortcuts folders on the left bar (Home, Documents, Downloads)
I get the following error
```
~/.config/awesome/widget/xdg-folders/documents.lua:-37: attempt to concatenate a nil value (global 'HOME')
```

**Comment by manilarome** [comment]
Thanks for reporting! Already [fixed](https://github.com/manilarome/the-glorious-dotfiles/commit/f88c8eb5a8382eed123c8bf629f4d11d1339e0e4) it!
