### ISSUE TITLE
Multi Monitor Setup

### ISSUE THREAD

**Issue by vivekkairi** [manilarome/the-glorious-dotfiles#35]
Hey,
Kudos for the amazing work. I'm having a multi monitor setup and I want to make monitor specific workspace like 1,2,3,4 workspace in monitor I and 5,6,7,8 in monitor II. Any leads on that?

I have used bspwm and i3, there it used to basic config file. How to do it here?

**Comment by manilarome** [comment]
Go to `awesome/configuration/client/rules.lua`  Set the screen on the property block. Something like this could work:

```lua
	ruled.client.append_rule {
		id         = "terminals",
		rule_any   = { 
			class = { 
				"URxvt",
				"XTerm",
				"UXTerm",
				"kitty",
				"K3rmit"
			},
		},
		except_any = {
			-- Exclude the QuakeTerminal
			instance = { "QuakeTerminal" }
		},
		properties = {
			tag = '1',
			switchtotag = true,
			draw_backdrop = false,
			size_hints_honor = false,
                        screen = 2
		}
	}
```

Now, all the terminal emulators will open in screen 2. That's the only solution I can think of.

**Comment by manilarome** [comment]
I'm gonna close this. If the solution didn't work, please re-open this again. :) Good day!
