### ISSUE TITLE
Does not work [GNawesOME]

### ISSUE THREAD

**Issue by ModdedGamers** [manilarome/the-glorious-dotfiles#40]
When I try to install it(I've installed awesome and rofi from air, as well as the correct picom.) When I copy the gnawesome config from dotfiles/config/awesome/gnawesome to $HOME/.config/awesome/gnawesome, then reload awesome, it doesn't work. Also, how do I install anything else besides the awesome theme? Thanks!

**Comment by Opticool** [comment]
I had the same issue at first. You have to rename gnawesome in your .config folder to awesome for awesomevm to recognize it

**Comment by ModdedGamers** [comment]
Ok

**Comment by manilarome** [comment]
@Opticool is right, the awesome folder contains both floppy and gnawesome setups. Don't copy the awesome folder, instead copy your chosen setup to `$HOME/.config/` then rename it to `awesome`.
