### ISSUE TITLE
[awesome configs] draw_backdrop + Move client to tag

### ISSUE THREAD

**Issue by ildar** [manilarome/the-glorious-dotfiles#41]
When `draw_backdrop=true` (for a modal dialog window), user moves it to different tag (with Super+Shift+#).

The window goes away but fog stays. Clicking on fog kills the dialog. Weird.
(this is the low priority issue)

**Comment by manilarome** [comment]
> The window goes away but fog stays

Yeah that's one of the flaws of the backdrop module, it stays on the screen even you changed the selected tag.

> Clicking on fog kills the dialog

That's normal. Click the backdrop will close the client associated with it.

Maybe I'll try to improve it to fix its drawbacks. Thanks for reporting.
