### ISSUE TITLE
[GNawesOME] moving bottom bar stuff into top  bar

### ISSUE THREAD

**Issue by Hkyx** [manilarome/the-glorious-dotfiles#42]
Hi, 

I want to move the tags and app launcher from bottom to the top panel, and move the clock to the right,  I tried many things but always got a new error. Can you give me some help on that please ?

thanks,

hk

**Comment by ildar** [comment]
For the clock try this:
https://github.com/manilarome/the-glorious-dotfiles/issues/38#issuecomment-600518799

**Comment by manilarome** [comment]
> app launcher

Make sure to also move the instantiation of widget to top panel

```
s.search      	= require('widget.search-apps')()
```


> tag list

The same as  app launcher move the line

```
local tag_list = require('widget.tag-list')
```

to top panel.

As for the clock, open `top-panel.lua` then

find the panel : setup {}

```lua
	panel : setup {
		layout = wibox.layout.align.horizontal,
		expand = "none",
		{
			layout = wibox.layout.fixed.horizontal,
			task_list(s),
			s.add_button
		}, 
                nil,
		{
			layout = wibox.layout.fixed.horizontal,
			spacing = dpi(5),
			s.updater,
			s.screen_rec,
			s.music,
		        s.float_panel ,  -- THIS IS THE CLOCK WIDGET
			s.end_session
		}
	}
```

**Comment by Hkyx** [comment]
Changed my panel for this but seems not work. If I relead, I saw the tag list in the up left corner, what I want but it's like a glitch of the ui because it disapear one second after.

my top panel:

`local awful = require('awful')
local beautiful = require('beautiful')
local wibox = require('wibox')
local gears = require('gears')

local icons = require('theme.icons')
local dpi = beautiful.xresources.apply_dpi

local clickable_container = require('widget.clickable-container')
local task_list = require('widget.task-list')
local tag_list = require('widget.tag-list')


local TopPanel = function(s)

	local panel = wibox
	{
		ontop = true,
		screen = s,
		type = 'dock',
		height = dpi(22),
		width = s.geometry.width,
		x = s.geometry.x,
		y = s.geometry.y,
		stretch = false,
		bg = beautiful.background,
		fg = beautiful.fg_normal
	}


	panel:struts
	{
		top = dpi(14)
	}


	panel:connect_signal(
		'mouse::enter',
		function()
			local w = mouse.current_wibox
			if w then
				w.cursor = 'left_ptr'
			end
		end

	)


	s.add_button = wibox.widget {
		{
			{
				{
					{
						image = icons.plus,
						resize = true,
						widget = wibox.widget.imagebox
					},
					margins = dpi(4),
					widget = wibox.container.margin
				},
				widget = clickable_container
			},
			bg = beautiful.transparent,
			shape = gears.shape.circle,
			widget = wibox.container.background
		},
		margins = dpi(4),
		widget = wibox.container.margin
	}

	s.add_button:buttons(
		gears.table.join(
			awful.button(
				{},
				1,
				nil,
				function()
					awful.spawn(
						awful.screen.focused().selected_tag.defaultApp,
						{
							tag = mouse.screen.selected_tag,
							placement = awful.placement.bottom_right
						}
					)
				end
			)
		)
	)
    s.search      	= require('widget.search-apps')()
    


	s.updater 		= require('widget.package-updater')()
	s.screen_rec 	= require('widget.screen-recorder')()
	s.music       	= require('widget.music')()
	s.end_session	= require('widget.end-session')()
	s.r_dashboard 	= require('layout.floating-panel')()


	panel : setup {
		layout = wibox.layout.align.horizontal,
		expand = "none",
		{
			layout = wibox.layout.fixed.horizontal,
			s.add_button
		},
		{
			layout = wibox.layout.fixed.horizontal,
			spacing = dpi(5),
            -- kept to get the hour and stuff stick on the right
			-- s.r_dashboard
		    -- s.clock_widget,
        },
		{
			layout = wibox.layout.fixed.horizontal,
			spacing = dpi(5),
			s.updater,
			s.screen_rec,
			s.music,
            s.r_dashboard,
			s.end_session
		}
	}

	return panel
end


return TopPanel
`

**Comment by manilarome** [comment]
It's because you didn't put the taglist in the panel.

```lua
panel : setup {
	layout = wibox.layout.align.horizontal,
	expand = "none",
	{
		layout = wibox.layout.fixed.horizontal,
                tag_list(s),  -- PUT IT HERE OR WHEREVER YOU WANT
		s.add_button,
	},
	{
		layout = wibox.layout.fixed.horizontal,
		spacing = dpi(5),
        -- kept to get the hour and stuff stick on the right
		-- s.r_dashboard
	    -- s.clock_widget,
    },
	{
		layout = wibox.layout.fixed.horizontal,
		spacing = dpi(5),
		s.updater,
		s.screen_rec,
		s.music,
        s.r_dashboard,
		s.end_session
	}
}
```

**Comment by Hkyx** [comment]
correct my bad ... jsut added the local on the top. 

In fact it add the tag_list not hte icons ... think i'll need to take more time to learn lua/awesome before modify this theme.

**Comment by manilarome** [comment]
> think i'll need to take more time to learn lua/awesome before modify this theme.

You can learn lua/awesome api by modifying that theme imo. That's what I did to learn awesome and lua :) I modified this [theme](https://github.com/PapyElGringo/material-awesome) to create an early version of Floppy. After learning some lua and awesomewm api, I created the new version Floppy that's in my repo right now. Happy hacking and good luck :)
