### ISSUE TITLE
[QUESTION] Lines

### ISSUE THREAD

**Issue by poiuedws** [manilarome/the-glorious-dotfiles#44]
was lines discontinued?
if so how come?, thanks in advance.

**Comment by manilarome** [comment]
At first, yes. But now, I'll just rewrite it. Don't close this issue, so I
can inform you if it's already finished. :)

**Comment by manilarome** [comment]
Hello, [linear](https://www.reddit.com/r/unixporn/comments/frn8tn/awesomewm_linear/) has be released(again). Hope you like it. It's a bit different but it has the same vibe I guess.
