### ISSUE TITLE
[GNawesOME] Battery discharging unusually fast

### ISSUE THREAD

**Issue by gunsimar** [manilarome/the-glorious-dotfiles#45]
I have tlp enabled (and started) and powertop calibrated as well. On my previous awesome setup i used to get 6 hours of battery life and on windows I usually get around 6-7. But using the Gnawesome setup I'm only getting 1-1.5 hours. 

running "powertop --html=powerreport.html" showed that awesome is the biggest power consumer with 14.9% usage and PW estimate of 286 mW with 12.3 Events/s.

I can't seem to figure out what's going on :/

**Comment by manilarome** [comment]
The power consumption is fine to me. Are you using the blur at full power?
