### ISSUE TITLE
Attempt to index a nil value (field 'gtk')

### ISSUE THREAD

**Issue by UltimateOmega** [manilarome/the-glorious-dotfiles#46]
When I start awesome this error is shown:
```
error while running function!
stack traceback
~/.config/awesome/theme/default-theme.lua:60:in function 'theme.default-theme.awesome_overrides'
~/.config/awesome/theme/init.lua:9: in main chunk
[C] in function 'require'
~/.config/awesome/rc.lua:20: in main chunk
error : ~/.config/awesome/theme/default-theme.lua:60: attempt to index a nil value (field 'gtk')
```

**Comment by ildar** [comment]
Sounds completely broken.
Does everything work with purged ~/.config/awesome? (default config)

**Comment by UltimateOmega** [comment]
> Sounds completely broken. Does everything work with purged ~/.config/awesome? (default config)

Awesome is fine when everything is purged.

**Comment by UltimateOmega** [comment]
> Sounds completely broken. Does everything work with purged ~/.config/awesome? (default config)

Awesome is fine when everything is purged.

**Comment by UltimateOmega** [comment]
oh snap!
my awesome is 4.2.
