### ISSUE TITLE
[Floppy][Bug?] Opening panels hides the program I'm using and notifications have an area around them that show the wallpaper.

### ISSUE THREAD

**Issue by spiwocoal** [manilarome/the-glorious-dotfiles#49]
Whenever I open one of the panels, the program I'm using hides and I see only the wallpaper and the panel, also, when a notification arrives or I open the calendar from the top panel, a weird area around the calendar/notification where a part of the program hides appears, I'm not sure if this is intended or not, but, at least to me, it's quite annoying.

Here you can see what I mean:

![ezgif-2-b04e27079cb8](https://user-images.githubusercontent.com/30442253/77335816-6f6e8700-6d05-11ea-8a03-504300ce2c1d.gif)

**Comment by ildar** [comment]
I've seen this behavior when my composite manager (picom per docs) wasn't
run. Check that.

BTW, I run standard compton and it is doing well. Picom isn't really
required.

**Comment by spiwocoal** [comment]
That worked, thanks!
