### ISSUE TITLE
blur-strength-slider home directory

### ISSUE THREAD

**Issue by danimateo** [manilarome/the-glorious-dotfiles#51]
`picom_dir=/home/gerome/.config/awesome/configuration/picom.conf` at line 54 should be `picom_dir=~/.config/awesome/configuration/picom.conf` . Tough one to catch since your setup is working lol.

**Comment by manilarome** [comment]
Oh shoot. I didn't noticed. Thanks for reporting!

**Comment by danimateo** [comment]
I did a full search for gerome, seems like that was the only one you missed.

**Comment by manilarome** [comment]
Fixed it. https://github.com/manilarome/the-glorious-dotfiles/commit/371607473dadacb20e158d02dad63b2d0e9b9035#diff-2c5e080576021b0ea3025bf858724dbeR54 Thanks again!
