### ISSUE TITLE
[question] Error and no Idea

### ISSUE THREAD

**Issue by Jim8Knopf** [manilarome/the-glorious-dotfiles#55]
Hey guys,
I try to understand how to config my awesome WM and i fund this project and it looks great.
So I tried to use it. Because I don't want to break it I run it in awmtt. Ther I got the error:
     ~/.config/awesome/layout/init.lua:23; attempt to index a nil value (field 'top_panel')
I tried both themes but the only different was the row of the error.
Also I tried to comment it out but it only creats more errors.
Could you explain a lua nob how I can use it?

**Comment by ildar** [comment]
What version of awesomewm? you need latest GIT head version

**Comment by Jim8Knopf** [comment]
Thanks that was the problem.
