### ISSUE TITLE
[BUG][Floppy] Applications have no lower bound

### ISSUE THREAD

**Issue by ProgrammerPlays** [manilarome/the-glorious-dotfiles#56]
Currently using the Floppy setup. The bottoms of my applications go off infinitely, causing me to not be able to fully see my applications. I'm using VirtualBox. If I run a reboot or a VirtualBox "forced shutdown", this issue doesn't occur, but it gives a 4:3, non-full resolution.

**Comment by manilarome** [comment]
Hey, can you send me a screenshot? Vbox works perfectly for me here

![image](https://user-images.githubusercontent.com/40349590/77864303-54969800-725a-11ea-952b-c00f196d0292.png)

**Comment by ProgrammerPlays** [comment]
@manilarome I'm referring to running Floppy in a VirtualBox instance, I'll send a screenshot when I have time

**Comment by manilarome** [comment]
> @manilarome I'm referring to running Floppy in a VirtualBox instance, I'll send a screenshot when I have time

Oh, sorry for the misunderstanding. Anyway, I tried running it in a vm(VBox) and it looks good to me with 1920x1080 resolution.

![screenshot2](https://user-images.githubusercontent.com/40349590/77869574-95e67200-7271-11ea-8687-5792539adbd1.png)
