### ISSUE TITLE
[BUG][FLOPPY] "End session" does not appear when in full resolution

### ISSUE THREAD

**Issue by ProgrammerPlays** [manilarome/the-glorious-dotfiles#57]
Same setup as https://github.com/manilarome/the-glorious-dotfiles/issues/56, VirtualBox config. 
Same occurances as well - if I reboot, its fine. Essentially, upon startup, the "End session" button does not appear, and I can't figure out how to make it appear.

**Comment by manilarome** [comment]
What is your screen resolution? I think it's recommended that you have 1366x768 and above.

**Comment by ProgrammerPlays** [comment]
@manilarome on the smaller resolution (less than 1366x768) its fine, but on 1920x1080 and a slightly shorter (height wise) version it does not appear. It basically only happens when the graphics drivers allow for proper resizing, when they don't it's fine.

**Comment by danimateo** [comment]
I use 1920x1080 and it works fine
