### ISSUE TITLE
[QUESTION] systray has a black background

### ISSUE THREAD

**Issue by RMTT** [manilarome/the-glorious-dotfiles#62]
![image](https://user-images.githubusercontent.com/20596599/78469236-e5d1a700-7751-11ea-9339-b1f8c056b89f.png)
i found the background is black rather than blur, i don't know why. I cannot find the config section of background of systray, is this a configuration error?

I use Linear theme,but other themes also have this issue.

**Comment by manilarome** [comment]
That's normal. :) AwesomeWM's doesn't support systemtray transparency so that's why.

**Comment by RMTT** [comment]
ok. thanks for your reply. It'a very beautify theme

**Comment by manilarome** [comment]
No problem and thanks :)
