### ISSUE TITLE
[ENHANCEMENT][LOCKSCREEN] PAM integration

### ISSUE THREAD

**Issue by xieve** [manilarome/the-glorious-dotfiles#63]
I'd like to see the lockscreen module use PAM instead of having a separate secrets config. I'm really not into saving my password in plain text.

**Comment by manilarome** [comment]
> I'd like to see the lockscreen module use PAM instead of having a separate secrets config. 

That's one of my goal too. But to be honest, I don't know how PAM works and I'm too lazy right now to dig into it right now. A PR is obviously appreciated. :D

> I'm really not into saving my password in plain text.

Yep, that's one of my concern too. 

I'll just pin this issue for now

**Comment by xieve** [comment]
I think I will fall back to [i3lock-color](https://github.com/Raymo111/i3lock-color) for the time being.

**Comment by RMTT** [comment]
Have done it by using a small lib.
lib code:
```C++
#include <lua.hpp>
#include <security/pam_appl.h>
#include <security/pam_misc.h>
#include <pwd.h>

struct pam_response *reply;

int simple_conversation(int num_msg, const struct pam_message **msg, struct pam_response **resp, void *appdata_ptr) {
    *resp = reply;
    return PAM_SUCCESS;
}


static int auth_current_user(lua_State *L) {
    int retval;

    const char *pass = luaL_checkstring(L, -1);

    uid_t uid = getuid();
    passwd *pw = getpwuid(uid);
    const char *user = pw->pw_name;

    pam_handle_t *pamh = NULL;
    struct pam_conv conv = {
            simple_conversation,
            NULL
    };
    retval = pam_start("login", user, &conv, &pamh);

    reply = (struct pam_response *) malloc(sizeof(struct pam_response));

    if (retval == PAM_SUCCESS) {
        reply->resp = strdup(pass);
        reply->resp_retcode = 0;

        retval = pam_authenticate(pamh, 0);    /* is user really user? */
    }

    /* This is where we have been authorized or not. */
    if (retval == PAM_SUCCESS) {
        lua_pushboolean(L, true);
    } else {
        lua_pushboolean(L, false);
    }
    return 1;
}


static const struct luaL_Reg lua_pam[] = {
        {"auth_current_user", auth_current_user}, /* names can be different */
        {NULL, NULL}  /* sentinel */
};

extern "C" int luaopen_liblua_pam(lua_State *L) {
    luaL_newlib(L, lua_pam);
    return 1;
}
```
changes lockscreen.lua:
```lua
local filesystem = require('gears.filesystem')
local config_dir = filesystem.get_configuration_dir()

package.cpath = package.cpath .. ";" .. config_dir .. "/library/?.so;"
local pam = require('liblua_pam')

...
-- Validate password
				local pam_auth = pam:auth_current_user(input_password)
				if pam_auth then
					-- Come in!
					self:stop()
					generalkenobi_ohhellothere()
				else
					-- F*ck off, you [REDACTED]!
					stoprightthereyoucriminalscum()
				end
...
```

Tested by myself, and it works well.

**Comment by manilarome** [comment]
Yow thanks for this! Damn. Couldn't do this myself!

**Comment by RMTT** [comment]
I can make a pr if you want.  (xd

**Comment by manilarome** [comment]
> I can make a pr if you want. (xd

Definitely! :)

**Comment by RMTT** [comment]
Have done.   : )

**Comment by manilarome** [comment]
> Have done. : )

Thank you! I have a question tho. How did you compile the library? Is there any required dependencies? I'm just really noob about PAM and C

**Comment by RMTT** [comment]
>  Is there any required dependencies

Nothing dependencies except the PAM.



> How did you compile the library?

i create a new ![repo](https://github.com/RMTT/lua-pam/tree/master) to place the lib, compile is easy, just two command:
```shell
cmake .
make
```
The code now is very easy but can use, i will improve it in the future.

**Comment by manilarome** [comment]
Oh nice, very cool. Thanks again! I'll just close this now but I'll leave it pinned.

**Comment by manilarome** [comment]
If you're using debian-based distros consider reading https://github.com/manilarome/the-glorious-dotfiles/issues/156 to avoid errors.
