### ISSUE TITLE
[ENHANCEMENT] PKGBUILDs/install scripts for all of the themes

### ISSUE THREAD

**Issue by xieve** [manilarome/the-glorious-dotfiles#64]
It'd be nice to have an installer. This would make this great project more accessible as an alternative to a "real" DE.

EDIT: As I have some basic experience in writing PKGBUILDs and a little more with shell scripts, let me know if you'd support an installer and I might contribute one

**Comment by manilarome** [comment]
I don't really have an experience/idea on how to package this to AUR or something but creating an install script is doable(for me).

**Comment by manilarome** [comment]
> As I have some basic experience in writing PKGBUILDs and a little more with shell scripts, let me know if you'd support an installer and I might contribute one.

Of course! That's great!

**Comment by xieve** [comment]
Only problem would be that the installer would have to override files, make automatic backups or abort installation if there is a config in place

**Comment by manilarome** [comment]
> Only problem would be that the installer would have to override files, make automatic backups or abort installation if there is a config in place

The script should move the current config folder to `awesome-backup` or something so the user can revert it.

> We'd also have to evaluate which of the config should be left to the user, even though it belongs to the rice, such as zsh.

I think it should be better if the script will only install the awesome setups not the whole dotfiles haha

**Comment by xieve** [comment]
Well, the prerequisites for GTK and QT ricing could also be included

**Comment by manilarome** [comment]
> Well, the prerequisites for GTK and QT ricing could also be included

Oh, okay gotcha! So we also need to include rofi-git, picom-kawase, and all the optional dependencies needed by widgets.

**Comment by RMTT** [comment]
A good idea.Maybe you can put the all configurable items to the home, include  some commands, such as the brightness adjustment, by the way, the xbacklight is incompatible with modesetting drm driver.

**Comment by manilarome** [comment]
>  Maybe you can put the all configurable items to the home

I think there's no need for that, because the only needed configuration are for picom and rofi which are stored in `awesome/configuration`. (I'm just talking about the awesome setups not the other dotfiles like ncmpcpp, mpd and etc.) 

> the xbacklight is incompatible with modesetting drm driver.

So let's use `light` instead?

**Comment by RMTT** [comment]
> > Maybe you can put the all configurable items to the home
> 
> I think there's no need for that, because the only needed configuration are for picom and rofi which are stored in `awesome/configuration`. (I'm talking about the awesome setups not the other dotfiles like ncmpcpp, mpd and etc.)
> 
> > the xbacklight is incompatible with modesetting drm driver.
> 
> So let's use `light` instead?

yeah, i have changed to light, it works fine, just modified the xbacklight command to light.

**Comment by manilarome** [comment]
> Maybe you can put the all configurable items to the home

Uhm... sorry, but right now I'll stick with `awesome/configuration` for rofi and picom. Just a preference of mine.

> it works fine

Then light it is. :)

**Comment by RMTT** [comment]
> Then light it is. :)

nice job! It's really a amazing theme.
But i encountered a new issue, the background of kitty and some other bars became black sometimes when i using some normal apps like chrome and thunderbird.
![image](https://user-images.githubusercontent.com/20596599/78550620-ef810a80-7836-11ea-82d6-a758ec775b44.png)
By the way, i think the `flameshot` is the best screenshot software of linux, maybe you can use it to replace the current one.

**Comment by manilarome** [comment]
> black sometimes when i using some normal apps like chrome and thunderbird.

It means the compositor is not working.

**Comment by xieve** [comment]
Alright, so I looked into this a little more, and a PKGBUILD would be a little more comfortable because it could reliably install dependencies, **but** awesome doesn't feature any kind of theme framework, and I don't think it's good practice to destructively overwrite global config files. So the options are either to write the config files to `/usr/lib/` and instruct the user to make a symbolic to `~/.config/awesome`, or to write an installation script that is clear about overwriting configuration but that only operates in userspace.

**Comment by manilarome** [comment]
I think the latter is better. Overwriting the global config file is a big no-no. Haha! I have a question, isn't it possible to just put the setups in `$HOME/.config` of the `$USER`? For example, just `cp *setups* $USER/.config/` then change its permission using `chown` or something?(I'm sorry I don't really have an idea about packaging stuffs)

**Comment by RMTT** [comment]
> I think the latter is better. Overwriting the global config file is a big no-no. Haha! I have a question, isn't it possible to just put the setups in `$HOME/.config` of the `$USER`? For example, just `cp *setups* $USER/.config/` then change its permission using `chown` or something?(I'm sorry I don't really have an idea about packaging stuffs)

Maybe you can try [chezmoi](https://github.com/twpayne/chezmoi)

**Comment by manilarome** [comment]
Thanks @RMTT. Will check that out. :)

**Comment by demostanis** [comment]
#133

**Comment by PoorPocketsMcNewHold** [comment]
To confirm everyone, I’ve used it to install it twice already, one with the linear setup and the second one with the floppy one. I can confirm it works wonderfully great!

**Comment by negativeExponent** [comment]
why is this pkgbuild missing a whole lots of things?

global appmenu requires awesome-freedesktop-git, not archlinux-xdg-menu

**Comment by manilarome** [comment]
> global appmenu requires awesome-freedesktop-git, not archlinux-xdg-menu

You can use both actually.  `awesome-freedesktop-git` is better tho because it automatically populates the `awful.menu` on start-up while the latter needs a manual intervention. Feel free to discuss it before I publish it on the AUR. @demostanis What's your opinion on this?

**Comment by manilarome** [comment]
Published [here](https://aur.archlinux.org/packages/the-glorious-dotfiles/). Huge thanks @demostanis  for your contribution.
