### ISSUE TITLE
[QUESTION][Floppy] Audio output switcher

### ISSUE THREAD

**Issue by chriske** [manilarome/the-glorious-dotfiles#65]
Hi there!

First of all, thank you for your work! It is amazing! I would like to have a question:

I installed awesomewm to an Ubuntu system with your dotfiles. Almost ( :) ) everything works fine, but I want to change my audio output to my monitor via HDMI. I tried to run the default Ubuntu "sound" utility, but it doesn't start in awesome at all. Can you help me please? I checked the config files, but didn't found anything related in them.

Thanks in advance!

**Comment by RMTT** [comment]
https://wiki.archlinux.org/index.php/PulseAudio/Examples#Simultaneous_HDMI_and_analog_output
try use pacmd to change output device?

**Comment by manilarome** [comment]
Thanks! Glad you like it.

Anyway, @RMTT is right. You can use the pacmd.

> but it doesn't start in awesome at all

You can run it on startup by adding it in `awesome/configuration/apps.lua`

**Comment by chriske** [comment]
Thanks for the tip! I tried it, but my HDMI output is not showing up at all :( I tried the HDMI method on that page, but pulseAudio didn't find it at all. I have an integrated GPU, maybe I will search for compatibility issues with pulseaudio. Thank you for your support!

**Comment by manilarome** [comment]
No problem! :) 

> I will search for compatibility issues with pulseaudio

Good luck!
