### ISSUE TITLE
[UPSTREAM][PICOM] Picom crashes on google chrome and thunderbird

### ISSUE THREAD

**Issue by RMTT** [manilarome/the-glorious-dotfiles#67]
I found the picom was kiied unexpectedly, but cannot find logfile of picom, i run the 'picom -h' but seems no log file item.

**Comment by manilarome** [comment]
use the manual: `man picom`

**Comment by manilarome** [comment]
Anyway, I can't reproduce your problem. I installed google-chrome and it doesn't crash picom. I think it's a driver or an upstream issue.

**Comment by RMTT** [comment]
the log file:
[picom.log](https://github.com/manilarome/the-glorious-dotfiles/files/4438470/picom.log)
Have several errors, but i don't know which one causes the killed.

**Comment by manilarome** [comment]
So chrome is causing the issue.

```
suddenly · Issue #67 · manilarome/the-glorious-dotfiles - Google Chrome"
[ 04/06/2020 20:43:19.682 ev_handle DEBUG ] event PropertyNo serial 0x00002652 window 0x02600001 "[BUG][floppy] picom be killed suddenly · Issue #67 · manilarome/the-glorious-dotfiles - Google Chrome"
[ 04/06/2020 20:43:19.857 ev_handle DEBUG ] event PropertyNo serial 0x00002658 window 0x02600001 "[BUG][floppy] picom be killed suddenly · Issue #67 · manilarome/the-glorious-dotfiles - Google Chrome"
```

I think you should report this to upstream. I can't really do anything about this. If you're using the tryone's branch of picom with kawase_blur, please consider reporting there. :)

**Comment by RMTT** [comment]
all right, thanks for your patient.But very weired, this is my second time installing the dotfiles.When the first time, it works well for a long time, also used chrome and thunderbird.And this time, it seems encountered strange issue, include the awesome-freedesktop, cannot show some icons, but the first time it shows all icons.
![image](https://user-images.githubusercontent.com/20596599/78564728-76da7800-784f-11ea-9f62-c4981d7919fd.png)

**Comment by manilarome** [comment]
> When the first time, it works well for a long time

Try using a default picom config first then try modifying it. Maybe it's a config problem or something

> cannot show some icons, but the first time it shows all icons.

Set your the menu icon theme in default-theme.lua the default icon is tela.

**Comment by RMTT** [comment]
> Try using a default picom config first then try modifying it. Maybe it's a config problem or something

It works well today  (xD 


> Set your the menu icon theme in default-theme.lua the default icon is tela.

I reinstall the tela icons from aur and fixed it, maybe because i don't install all colors of tela.

**Comment by manilarome** [comment]
> It works well today (xD

nice

> maybe because i don't install all colors of tela.

Yeah because we are using the blue dark colors
