### ISSUE TITLE
[BUG][Floppy] Shouldn't restore minimized be in global instead of client?

### ISSUE THREAD

**Issue by danimateo** [manilarome/the-glorious-dotfiles#68]
Shouldn't this:
```
awful.key(
        {modkey, 'Control'},
        'n',
        function()
            local c = awful.client.restore(awful.screen.focused())
            -- Focus restored client
            if c then
                client.focus = c
                c:raise()
            end
        end,
        {description = 'restore minimized', group = 'screen'}
    ),
```
be in `global.lua` instead of `client/keys.lua` ? If it's in the latter, when all clients are minimized, nothing happens when pressing the shortcut. Also, `Super + n` seems to be missing from `client/keys.lua`. Is there any reason why the following is removed?
```
awful.key(
        {modkey},
        'n',
        function(c)
            c.minimized = true
        end,
        {description = "minimize client", group = 'client'}
    ),
```

**Comment by manilarome** [comment]
Yeah, the keybindings are a mess. I'll try to clean it up later

**Comment by manilarome** [comment]
Done https://github.com/manilarome/the-glorious-dotfiles/commit/34f2b15143c54ef7715e28e1d1ea27f8a816a6bd 

Thanks for reporting this!
