### ISSUE TITLE
[FR][GNawesome] screen corner action

### ISSUE THREAD

**Issue by ildar** [manilarome/the-glorious-dotfiles#71]
While these awesome-wm configs are cool and awesome, one supa-ficha is missing:
when the mouse pointer hangs in a screen corner for some time, some action can be done.
Possible?

**Comment by manilarome** [comment]
I've been thinking about that. We can create a module for that but for what purpose? (I'm just curious. Never used that functionality before) We can use xdotool for that and just run it on startup without creating a module. We can also use a tiny hidden wiboxes then put them on the screen edges then add a `mouse::enter` connect signal to execute a `gears.timer` or something that will execute a callback.

**Comment by ildar** [comment]
>
> We can create a module for that but for what purpose? (I'm just curious.
> Never used that functionality before)
>
Classical use: top left corner — app launcher (rofi),
top right — window list

**Comment by manilarome** [comment]
> Classical use: top left corner — app launcher (rofi),
top right — window list

Okay, fair enough. I can start with the module later. I'm just busy right
now fixing an OSD module bug.

> top right - window list

We don't have a window list widget or something right now. Should we use
`rofi -show window` for this?

**Comment by manilarome** [comment]
> Should we use `rofi -show window` for this?

The window switching using rofi is not working with awesome(just tested it)
so any alternative?

**Comment by manilarome** [comment]
https://github.com/awesomeWM/awesome/issues/3047

**Comment by RMTT** [comment]
> The window switching using rofi is not working with awesome(just tested it) so any alternative?

Oh, I also encountered this issue when using rofi, is there a way to use rofi to call some scripts?

**Comment by manilarome** [comment]
> is there a way to use rofi to call some scripts?

Yes. The web search in is using a python-script. For example:

```
rofi -show Something -modi Something:script.sh -theme rofi.rasi
```

**Comment by manilarome** [comment]
Uhm... sooo I encountered a problem while creating the hot corners module. The panels/wiboxes are ontop instead of the hot corners. The cause of the problem is that the panels are slower to load that's why the hotcorners are being 'pushed down' or being 'covered' by it. 

![image](https://user-images.githubusercontent.com/40349590/78765115-216eaa00-79ba-11ea-9189-6a2aa98e36e5.png)

**Comment by manilarome** [comment]
```lua
local wibox = require('wibox')
local awful = require('awful')
local gears = require("gears")
local beautiful = require('beautiful')

local dpi = require('beautiful').xresources.apply_dpi

screen.connect_signal("request::desktop_decoration", function(s)


	tl_x = s.geometry.x
	tl_y = s.geometry.y
	s.corner_tl = wibox {
		x = dpi(tl_x),
		y = dpi(tl_y),
		visible = true,
		screen = s,
		ontop = true,
		opacity = 1,
		height = dpi(5),
		width = dpi(5),
		type = 'utility',
		bg = '#ff00ff',
	}
	s.corner_tl:connect_signal(
		"mouse::enter", 
		function()
			gears.timer.start_new(0.5, 
				function()
					require('naughty').notification({message='123123'})
				end
			)
    	end
    )

	tr_x = s.geometry.x + (s.geometry.width - 1)
	tr_y = s.geometry.y
	s.corner_tr = wibox {
		x = dpi(tr_x),
		y = dpi(tr_y),
		visible = true,
		screen = s,
		ontop = true,
		opacity = 1,
		height = dpi(1),
		width = dpi(1),
		type = 'utility',
		bg = '#ff00ff',
	}

	br_x = s.geometry.x + (s.geometry.width - 1)
	br_y = s.geometry.y + (s.geometry.height - 1)
	s.corner_br = wibox {
		x = dpi(br_x),
		y = dpi(br_y),
		visible = true,
		screen = s,
		ontop = true,
		opacity = 1,
		height = dpi(1),
		width = dpi(1),
		type = 'utility',
		bg = '#ff00ff',
	}

	bl_x = s.geometry.x
	bl_y = s.geometry.y + (s.geometry.height - 1)
	s.corner_bl = wibox {
		x = dpi(bl_x),
		y = dpi(bl_y),
		visible = true,
		screen = s,
		ontop = true,
		opacity = 1,
		height = dpi(1),
		width = dpi(1),
		type = 'utility',
		bg = '#ff00ff',
	}

end)


local move_on_top = function()
	focused = awful.screen.focused()

	focused.corner_tl.ontop = true
	focused.corner_tr.ontop = true
	focused.corner_tr.ontop = true
	focused.corner_bl.ontop = true
end


client.connect_signal(
	"property::fullscreen", 
	function(c)

		focused = awful.screen.focused()

		if c and not c.fullscreen then
			move_on_top()
		end
		move_on_top()
	end
)
```

**Comment by manilarome** [comment]
So yeah. We will not use `input_passthrough` because it will render the widgets in the panels useless.  Although I already managed moving the hot corners on top while fullscreen, the module will still be useless if it's not usable when not in fullscreen mode.

If you have an idea, please open a PR or suggest here.

Here's my current code:

```lua
local wibox = require('wibox')
local awful = require('awful')
local gears = require("gears")
local beautiful = require('beautiful')

local dpi = require('beautiful').xresources.apply_dpi

screen.connect_signal("request::desktop_decoration", function(s)

	s.corner_tl = wibox {
		x = dpi(s.geometry.x),
		y = dpi(s.geometry.y),
		visible = true,
		screen = s,
		ontop = true,
		opacity = 1,
		height = dpi(1),
		width = dpi(1),
		type = 'utility',
		bg = '#ff00ff',
	}
	s.corner_tl:connect_signal(
		"mouse::enter", 
		function()
			gears.timer.start_new(0.3, 
				function()
					require('naughty').notification({message='123123'})
				end
			)
    	end
    )

	s.corner_tr = wibox {
		x = dpi(s.geometry.x + (s.geometry.width - 1)),
		y = dpi(s.geometry.y),
		visible = true,
		screen = s,
		ontop = true,
		opacity = 1,
		height = dpi(1),
		width = dpi(1),
		type = 'utility',
		bg = '#ff00ff',
	}

	s.corner_br = wibox {
		x = dpi(s.geometry.x + (s.geometry.width - 1)),
		y = dpi(s.geometry.y + (s.geometry.height - 1)),
		visible = true,
		screen = s,
		ontop = true,
		opacity = 1,
		height = dpi(1),
		width = dpi(1),
		type = 'utility',
		bg = '#ff00ff',
	}

	s.corner_bl = wibox {
		x = dpi(s.geometry.x),
		y = dpi(s.geometry.y + (s.geometry.height - 1)),
		visible = true,
		screen = s,
		ontop = true,
		opacity = 1,
		height = dpi(1),
		width = dpi(1),
		type = 'utility',
		bg = '#ff00ff',
	}

end)


local move_to_top = function()
	focused = awful.screen.focused()

	focused.corner_tl.ontop = true
	focused.corner_tr.ontop = true
	focused.corner_tr.ontop = true
	focused.corner_bl.ontop = true
end


client.connect_signal(
	"property::fullscreen", 
	function(c)
		focused = awful.screen.focused()
		if c and not c.fullscreen then
			move_to_top()
			return
		end
		move_to_top()
	end
)
```

**Comment by manilarome** [comment]
Another possible scenario to fix/workaround it is to add a delay before showing/creating it by using `gears.timer`.

**Comment by manilarome** [comment]
Done! https://github.com/manilarome/the-glorious-dotfiles/commit/b7d964ac2140cc0673bbd06f14c8d35ba0e29b07 I found a workaround. It's not clean but it works so. Please, suggest a better callback for the hot-corners.

**Comment by manilarome** [comment]
Hey @ildar , sorry for this but I decided to not use this module in my setups. It's because I can't implement it well with them. But I moved the module to my other [repo](https://github.com/manilarome/awesome-glorious-widgets) that can be found [here](https://github.com/manilarome/awesome-glorious-widgets/tree/master/hot-corners) . :) Thanks again.

**Comment by ildar** [comment]
That's very nice. Thank you for implementing.
I did a test today. Well, tl (corner) works great but others seem not
reacting. Maybe something with x/y ?
Thanks again.

**Comment by manilarome** [comment]
> I did a test today. Well, tl (corner) works great but others seem not
reacting. Maybe something with x/y ?

Please consider opening an issue on the other [repo](https://github.com/manilarome/awesome-glorious-widgets). Thanks! :)
