### ISSUE TITLE
[Spotify cover]How does it work ?

### ISSUE THREAD

**Issue by BigfootN** [manilarome/the-glorious-dotfiles#73]
Hello,

Just to be honest, I have not tried/installed your dotfiles, but I have a question concerning the album cover download from spotify.

```
local get_art_url = [[
	dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
	string:'org.mpris.MediaPlayer2.Player' string:'Metadata' | 
	egrep -A 1 "artUrl"| egrep -v "artUrl" | awk -F '"' '{print $2}'
	]]
```

When using this command I get the url of the album cover, but it never works. When trying to download it I get a 404 error.

Thank you very much for any help.

**Comment by manilarome** [comment]
I'm not using the spotify-music-updater of the music widget. I can safely say that the development for that has been postponed. 

> When using this command I get the url of the album cover, but it never works. When trying to download it I get a 404 error.

**Comment by manilarome** [comment]
Try opening the spotify application then run the dbus command in the terminal. IIRC that dbus command will return the URL of the album art. Good luck :)

**Comment by BigfootN** [comment]
Thank you very much for your answer, I am quite relieved to know that I am not the only one.

Just so you know, spotify is opened and I get an url of type: `https://open.spotify.com/image/<some number and letters>`

**Comment by manilarome** [comment]
You're welcome!

> Just so you know, spotify is opened and I get an url of type:
https://open.spotify.com/image/<some number and letters>

Yeah that should be the output. :) Goodluck!

**Comment by BigfootN** [comment]
Just so you know I found [this](https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/td-p/4920104). Hoping it's any help to anyone.
