### ISSUE TITLE
[QUESTION] Rofi not working on Discrete card

### ISSUE THREAD

**Issue by MaksVal** [manilarome/the-glorious-dotfiles#75]
Hi! 
Thanks for your configs. Your awesome wm is beautiful. 

I have Thinkpad t420s with a discrete card by Nvidia. Rofi is good working when I run WM on intel(X11) with this theme config: `configuration/rofi/appmenu/rofi.rasi`. 
If I running WM on Nvidia chip I have the error of rofi:
```
config.monitor = primary Could not find monitor
```
I read the documentation by rofi: https://github.com/davatorium/rofi/wiki/WindowPosition#monitor
Why you use a "primary" variable? I try to change the config of rofi and it is working now:
![image](https://user-images.githubusercontent.com/10114447/78862310-be275b00-7a3f-11ea-9ec0-ab5c15907170.png)

Thanks.

**Comment by manilarome** [comment]
You should set your active monitor as primary using arandr or xrandr. I
forgot to add this issue in the wiki, my bad.
