### ISSUE TITLE
get rid of binaries as much as possible

### ISSUE THREAD

**Issue by ildar** [manilarome/the-glorious-dotfiles#78]
I'm serious about running binaries from external sources. Closed-source are especially disgusting.
Meanwhile I suggest replacing unnecessary binaries.

- `capschecker`: can be easily replaced with `xset q`

**Comment by manilarome** [comment]
This is the [source])(https://gist.github.com/manilarome/fd9a12b3fc5abf7c1a4b4bd8fd498984) of the capschecker. 

> capschecker: can be easily replaced with xset q

I considered using this back then but my string manipulation is not good enough haha

**Comment by manilarome** [comment]
Hey, I'm closing this now. I will not implement/use `xset -q` as an alternative for `capschecker` because it will be an another dependency(`xorg-xset`).  I'll just put a source code links in the wiki.

**Comment by ildar** [comment]
I doubt that you can remove xset safely from your system:
> $ rpm -e --test xset
> error: Failed dependencies:
> xset is needed by (installed) xdg-utils-1.1.3-alt5.noarch
> xset is needed by (installed) xorg-server-2:1.20.4-alt2.x86_64
> xset is needed by (installed) xorg-utils-7.8-alt9.x86_64

I'll try to code that.

**Comment by manilarome** [comment]
I doubt that you can remove xset safely from your system:

> You're right. I'm just too dumb to check it out.

I'll try to code that.

> Okay thanks!

**Comment by manilarome** [comment]
Merged https://github.com/manilarome/the-glorious-dotfiles/pull/88. So the only left is the lua-pam, but we don't have an alternative for that yet and we have a source code for that. So closing this of the meantime.
