### ISSUE TITLE
[FR] XDG compliance

### ISSUE THREAD

**Issue by ildar** [manilarome/the-glorious-dotfiles#79]
De-facto standard xdg tools help dealing with desktop staff in uniform way.
Essentially [xdg-user-dirs](https://freedesktop.org/wiki/Software/xdg-user-dirs/) will point you to Screenshots and Videos dirs.

**Comment by ildar** [comment]
BTW https://awesomewm.org/apidoc/utility_libraries/gears.filesystem.html#get_xdg_data_dirs

**Comment by manilarome** [comment]
Is this what you want to happen? https://github.com/manilarome/the-glorious-dotfiles/commit/473d1afa98ba7a8b21514ab01b277231bf2460a7

**Comment by ildar** [comment]
Looks great!
Now `snap` and video-capturing left!

**Comment by manilarome** [comment]
Done! https://github.com/manilarome/the-glorious-dotfiles/commit/ac69af7e5aa32fb3cb8195b763bb9a9488002f13 https://github.com/manilarome/the-glorious-dotfiles/commit/dee40de33e0bd514db1d81d6ae1fdd3a52fac65f 

Thanks for suggesting this! Closing this now

**Comment by ildar** [comment]
Emm, plz also
https://github.com/manilarome/the-glorious-dotfiles/blob/master/config/awesome/gnawesome/widget/music/mpd-music-updater.lua#L24

**Comment by manilarome** [comment]
https://github.com/manilarome/the-glorious-dotfiles/commit/2e5e4b10697a5922ff6ea24b795f363fb5085b1f

**Comment by ildar** [comment]
thanks!
