### ISSUE TITLE
[QUESTION] Config version tagging

### ISSUE THREAD

**Issue by zenfailure** [manilarome/the-glorious-dotfiles#83]
Hi,
Sorry for the format. The config looks very nice. Nice work. Howevre, it'd be nice to tag the configs with their corresponding awesome versions, no? That way, people could just try them out whatever release their distribution is running?

Regards

**Comment by manilarome** [comment]
Uhm... I think there's no point on doing that, because the only awesome version we are using is the `git-master branch` and I have no plan on supporting the stable 4.3v.  Thanks for suggestion tho :)
