### ISSUE TITLE
[QUESTION][ANY] Installation guide mistake at the step #5

### ISSUE THREAD

**Issue by kynguyen98** [manilarome/the-glorious-dotfiles#84]
Okay so I follow his installation guide and it was a straight forward guide but when it comes to the step where you copy the setup 
```
cp -r the-glorious-dotfiles/config/awesome/floppy $HOME/.config/awesome
```
this copy the folder and put it in the awesome not the content of the setup file so I have to take it out from the floppy or any setup file and put it outside the awesome folder in order for this setup to work

**Comment by manilarome** [comment]
> cp -r the-glorious-dotfiles/config/awesome/floppy $HOME/.config/awesome

This is correct **if** you don't have an `awesome` folder in your `~/.config`. But yeah, I should've wrote this in the instructions. :grimacing: Thanks for reporting this! :) I'll fix this later.
