### ISSUE TITLE
notification's timeout ignored

### ISSUE THREAD

**Issue by ildar** [manilarome/the-glorious-dotfiles#86]
`notify-send -t 20000 1 2` doesn't hold for 20 seconds on screen.

**Comment by manilarome** [comment]
This is an upstream issue. I think these issues are related to this. https://github.com/awesomeWM/awesome/issues/3057 https://github.com/awesomeWM/awesome/issues/3049

**Comment by ildar** [comment]
Nope. I checked the above command before filing the issue. Pure AwesomeWM
works as expected.

**Comment by ildar** [comment]
please reopen

Also note that `critical` notifications last more. So you seem to override
the timeout in your config.

**Comment by manilarome** [comment]
Oh yeah

**Comment by manilarome** [comment]
Oh, I'm sorry about that. I just thought naughty will override the timeout I set in `notifications.lua` which is `0`. It works perfectly before until the recent `naughty` update. Thanks for the fixed. Will merge it now. :)

**Comment by manilarome** [comment]
I can still reproduce this issue. But somehow, removing the `ruled.notifications` allows the overriding of the timeout using notify-send. `naughty` is weird

**Comment by manilarome** [comment]
https://github.com/manilarome/the-glorious-dotfiles/pull/106/commits/88f2f906441e960760a280db348bde3c7a0d8f26
