### ISSUE TITLE
[QUESTION] startup error nil value

### ISSUE THREAD

**Issue by syminical** [manilarome/the-glorious-dotfiles#89]
Hi,

I am a noob :)

I tried to follow your install guide, and it looked like everything installed correctly, but when I start up awesome I get a red box with this message:
```"Oops, an error happened during startup!
 error while running function!
 stack traceback:
     /home/syminical/.config/awesome/theme/default-theme.lua:60: in
 function 'theme.default-theme.awesome_overrides'
     /home/syminical/.config/awesome/rc.lua:20: in main chunk
 error: /home/syminical/.config/awesome/theme/default-theme.lua:60: attempt to
 index a nil value"
```

I have these installed (from `yay -Q`)
- **awesome-git**            4.3.814.g158cc37a0-1 
- **rofi-git**                     1.5.4.r89.g75871499-1
- **picom-tryone-git**     1417_Next.136.g5ed6387_2020.04.12-1

The error goes away if I delete ~/.config/awesome, and it happens with both floppy and linear.

I used `yay -Syu awesome-git --removemake` to install awesome-git. Is there a way to check which branch is installed? I am not sure what to try now.

**Comment by manilarome** [comment]
The line 60 of default-theme.lua has the `beautiful.gtk` api of awesome that gets the color of gtk theme that you're using. Can you please open `lxappearance-gtk` then set your preferred gtk theme then reload awesomewm?

**Comment by manilarome** [comment]
Please report back if my answer fixed your problem, so I can write it in the wiki. Thanks :)

**Comment by syminical** [comment]
Now I have **lxappearance** and **tela** installed. I think I have selected an icon theme in lxappearance.

After that I got a different error, but I installed `gtk3` and it looks like it is working now.

Thank you! :)

**Comment by manilarome** [comment]
Nice! Thanks for reporting! :) Closing this now.
