### ISSUE TITLE
[FR] enhance to the full-featured Dark Mode

### ISSUE THREAD

**Issue by ildar** [manilarome/the-glorious-dotfiles#92]
this setup already has Blue Light Filter (as opposite to the Red Shift, I guess?)

But I suggest you to advance to the full-featured Dark Mode, i.e. tell toolkits to switch to the Dark theme. That is: the switch should ask XSETTINGS daemon that hints toolkits. E.g. I use GNOME gsd-xsettings.

Then I guess Night mode magic can show up.

**Comment by manilarome** [comment]
> tell toolkits to switch to the Dark theme. That is: the switch should ask XSETTINGS daemon that hints toolkits. 

This was planned long ago but I think we will have a problem if the user(like me) is using both GTK and Qt apps. If I will to create this, I should design it to change both of the toolkits' theme. And I feel that adding this will make the setups more bloated than it should be because we will add a GTK/Qt theme as an optional dependency.

**Comment by ildar** [comment]
Not quite. This should work on the fly:
https://developer.gnome.org/gtk3/unstable/GtkSettings.html#GtkSettings--gtk-application-prefer-dark-theme
I just don't know what DBus message to send to the daemon so it switches
the property.

**Comment by manilarome** [comment]
I'll look into it but I right now cannot promise you that I will implement this because this is outside of the scope I've planned for the setups.

Prerequisites for this feature request?

+ Settings daemon??? - to change gtk3 themes on the fly so that we don't need to close the app before updating its theme?
+ Dbus signal to switch between color schemes. - top priority
+ GTK3 theme(light/dark)? Best theme for the setup? (that's why i'm using Qt apps because the best match for the blurry environment is a blurry ui (Qt + Kvantum engine). They compliment each other very well. Example:
    ![Example](https://github.com/manilarome/the-glorious-dotfiles/blob/master/images/setup-big.png)

Implementing this FR is possible but first we need to tackle the prereqs above. 

I'll just leave this open for now.

**Comment by ildar** [comment]
I suggest not load prerequisites. Just code the dbus signal. If it works —
fine! If not — user should take care on himself.

**Comment by ildar** [comment]
I diged a little further:
1. DBus is of no use here, just DConf.
2. Gnome guys still didn't make it changeable on the fly:
https://gitlab.gnome.org/GNOME/gtk/-/issues/1919
3. Yes, you're right: switching themes should work just fine.

So adding dconf spawn call to the "Blue Light" switch should work for me )))

**Comment by manilarome** [comment]
> DBus is of no use here, just DConf.

So I tried changing the gtk3 theme using

```bash
$ gsettings set org.gnome.desktop.interface gtk-theme ThinIce
```
It updates the value in dconf but the theme was not applied on the applications, so we definitely need a settings daemon like xfsettingsd or gnome-settings-daemon.

> Gnome guys still didn't make it changeable on the fly:

You can if you have settings daemon. Look at [this](https://youtu.be/8fBTGGL09No?t=93).

> So adding dconf spawn call to the "Blue Light" switch should work for me )))

If we will implement this this should should have a separate button to toggle it.

Conclusion: I'm not really a fan of installing a settings daemon (xfsettingsd/gnome-settings-daemon). :grimacing: So I'll stick with editing the main configuration file for the setups.

**Comment by ildar** [comment]
actually for this to work, you only need to launch
`/usr/libexec/gsd-xsettings`. Kinda light!

**Comment by manilarome** [comment]
Uhm I don't have a `/usr/libexec/gsd-xsettings` of `gsd-xsettings` installed. Sorry, but I'm not really planning to add this on the setup, right now. Maybe this could be a separate module like the `hot-corners` and I'll just put it on the other repo. So in the meantime, I'll just leave this open

**Comment by ildar** [comment]
JFYI: gsd == gnome-settings-daemon
the binary is the part of that package. It may be in another place if FS.

**Comment by manilarome** [comment]
Okay, thanks for the info! I'll try to create a separate module for this but I can't really promise you that I will create this right away. Maybe we should use a different settings daemon. GSD installs gnome-desktop and libgweather and I don't think the setups(or I) needs them haha.

**Comment by ildar** [comment]
I don't think a new module is required.
For me ideal way will be to add another action to the "Blue Light Filter".
The action is exec-ing dconf command line to switch theme.
Simple!

So IMHO this FR may be safely closed.

**Comment by manilarome** [comment]
> I don't think a new module is required. For me ideal way will be to add another action to the "Blue Light Filter".

UI/UX-wise it's a bad idea. The button is labeled 'blue light filter' so it should just toggle the filter.

Anyway, I tried implementing it. This is the result:

![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/40349590/79549754-f6770b00-80c9-11ea-933a-94235d68fdd0.gif)


Just download the gsd then run it. After that replace this [function](https://github.com/manilarome/the-glorious-dotfiles/blob/7086d8b4a0303bfb3b402226d9e79b27ff5a5650/config/awesome/gnawesome/widget/blue-light/init.lua#L77-L93) to this:


```lua
local toggle_action = function()
	awful.spawn.easy_async_with_shell(
		[[
		pgrep redshift > /dev/null && (redshift -x && pkill redshift && echo 'OFF') || 
		(echo 'ON' && redshift -l 0:0 -t 4500:4500 -r &>/dev/null &)
		]],
		function(stdout)
			if stdout:match('ON') then
				blue_light_state = true
				awful.spawn.with_shell('gsettings set org.gnome.desktop.interface gtk-theme "Equilux"')
			else
				blue_light_state = false
				awful.spawn.with_shell('gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"')
			end
			update_imagebox()
		end
	)
end
```

But I'm really sorry I don't really want to install a settings daemon right now. And I'm really happy with Qt/Kvantum. :)

**Comment by ildar** [comment]
yes, sure, thanks!

**Comment by manilarome** [comment]
I'll implement this on my setups if there's a GTK theme that will blend with it or if Qt severes their ties with KDE(hopeful that this will not happen). Thanks again! Closing this now

**Comment by ildar** [comment]
ok, just FYI, I did it with
https://github.com/ildar/the-glorious-dotfiles/commit/e696c81d8dd9f145dd8ce8cfe123404322b6ed09
