### ISSUE TITLE
How can I have an application open in the current workspace?

### ISSUE THREAD

**Issue by ChapelCone** [manilarome/the-glorious-dotfiles#94]
Hi, I've been using this rice for a while now. I really like it, but I was wondering if it's possible to disable programs only opening in certain workspaces. Every time I open a terminal I have to switch workspace to use it. Can I disable this feature for certain programs? I would like the program to open in my current workspace. Thanks and sorry for the noob question.

**Comment by manilarome** [comment]
In `awesome/configuration/client/rules` find the tag of the terminal/app then change the property `switchtotag` to false

**Comment by manilarome** [comment]
Tip: You can use the quake terminal module by pressing <kbd>Super + ~</kbd>. It will open on the current tag you are in and will be in sticky mode.Sso it means it'll follow you wherever the tag you are. Closing this for now. Reopen my answer doesn't work. Good luck!
