### ISSUE TITLE
[QUESTION] Lines

### ISSUE THREAD

**Issue by Rokre** [manilarome/the-glorious-dotfiles#96]
Hello, how can I change the tag list icons to use for example a font icon like nerd font?

**Comment by manilarome** [comment]
> Hello, how can I change the tag list icons to use for example a font icon like nerd font?

Uhm you can create a new tags with different properties. Tbh I don't know how to change the taglist icons to a font. I didn't create the taglist andit was designed to only show the tag icons. The documentation is [here](https://awesomewm.org/apidoc/core_components/tag.html#awful.tag.add) and it provides an instruction on how to do it. You can alter the tags in `awesome/configuration/tags/init` and the main taglist widget is in `awesome/widget/tag-list.lua`

**Comment by NeoScaler** [comment]
@manilarome May I ask which icon set you used for the tag list? I want to exchange a few.

**Comment by manilarome** [comment]
The name's `Tela`(blue-dark variant) and you can find it in `awesome/themes/icons/tag-list/`.
